{
  "hash": "298d8af4a61f36e2a740e801d0e4fab3",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: \"Pure-Premium Tutorial\"\n---\n\nWe estimate the expected claim cost per year of cover for a policy: its\npure premium. We compare two approaches, predicted frequency multiplied by\npredicted average claim amount, and a direct Tweedie prediction. Fitting\nboth with GLUM and LightGBM gives four estimates for the same test policies.\n\nIf you are new to pricing models, start with the\n[targets and weights](index.qmd#targets-and-weights), then read in order.\nWe prepare and split the data, explore uncapped training outcomes, select\nTweedie power, fit GLUM, check its working distributions, fit LightGBM,\nand evaluate the four estimates. The collapsed “Look inside” notes explain\nthe mathematics and library functions in more detail.\n\nIf you already fit pricing models, use the\n[conditional diagnostics](#sec-conditional-diagnostics) to review the\ndistribution assumptions, then follow the [test audit](#sec-test-audit)\nthrough accuracy, calibration, and ranking to the\n[recorded findings](#sec-test-findings).\n\nRun the Python cells in order, whichever reading path you choose. The full\nfreMTPL2 run can take a while; use a small sample to check that the notebook\nworks, and the full data for actuarial conclusions.\n\n::: {#f44098db .cell execution_count=1}\n``` {.python .cell-code}\nfrom inspect import getsource\n\nimport matplotlib.pyplot as plt\nimport numpy as np\nimport pandas as pd\nfrom IPython.display import Markdown, display\nfrom scipy.stats import gamma, poisson\n\nfrom nonlife_pureprem import (\n    TARGET_SPECS,\n    coefficient_relativity_table,\n    evaluate_predictions,\n    exposure_balanced_double_lift_table,\n    exposure_balanced_lift_table,\n    fit_gamma_dispersion,\n    fit_negative_binomial_shape,\n    fit_tweedie_dispersion,\n    fit_glum_inference,\n    fit_glum_predictive,\n    fit_lightgbm,\n    gamma_ccdf_diagnostic,\n    gini,\n    grouped_calibration,\n    lift_diagnostics,\n    lightgbm_frame,\n    load_mtpl2,\n    lorenz_curve,\n    lorenz_dominance_table,\n    make_splits,\n    conditional_dispersion_diagnostic,\n    conditional_dispersion_table,\n    poisson_ccdf_diagnostic,\n    portfolio_calibration_table,\n    print_frame,\n    select_tweedie_power,\n    target_and_weight,\n    target_weight_table,\n    tweedie_ccdf_diagnostic,\n    weighted_empirical_ccdf,\n    weighted_mean_deviance,\n    hexbin_grid\n)\n\n\ndef show_source(fn):\n    \"\"\"Render a library function as a syntax-highlighted code block.\"\"\"\n    display(Markdown(f\"```python\\n{getsource(fn)}\\n```\"))\n\n\nMODEL_COLORS = {\n    \"observed\": \"#000000\",\n    \"GLUM\": \"#E69F00\",\n    \"LightGBM\": \"#56B4E9\",\n    \"GLUM frequency x severity\": \"#E69F00\",\n    \"LightGBM frequency x severity\": \"#56B4E9\",\n    \"GLUM Tweedie\": \"#009E73\",\n    \"LightGBM Tweedie\": \"#D55E00\",\n}\n```\n:::\n\n\n::: {.callout-note}\n## A note on figures\n\nThe matplotlib cells display each chart alongside its plotting code.\nLine charts share one colourblind-safe Okabe–Ito palette assigned per model\n(`MODEL_COLORS` in the setup cell); dense two-dimensional bins use the\nperceptually uniform, colourblind-safe cividis colormap. The library's\n`save_core_figures` helper writes the four core figures to disk for CLI runs.\n:::\n\n## Set a reproducible run\n\nKeep the full-data defaults below when selecting a rate model; set `n_samples`\nonly for a quick software check. Fix the random seed, shared data splits, and\ntuning budgets before looking at results.\n\n::: {#6c924eab .cell execution_count=2}\n``` {.python .cell-code}\nn_samples = None  # e.g. 10_000 for a quick software smoke run\nn_alphas = 30\nmax_rounds = 2_000\nearly_stopping_rounds = 50\n```\n:::\n\n\n## Build audited frequency, severity, and pure-premium targets\n\nFrequency and pure premium are rates per unit exposure; severity is an\naverage amount per claim.\n\nLoad policy and claim tables, remove non-positive claims, cap each claim at\nEUR 100,000, cap exposure at one year, aggregate claims to policy level, and\nconstruct the three targets. Claim counts come from the positive claim\nrecords, not the source `ClaimNb`, so frequency and pure premium share one\nclaim set; the structural audit reports both totals and the disagreeing rows.\nBoth policy identifier columns must contain finite integers within the int64\nrange before conversion or joining. Numeric strings and integer-valued floats\nare accepted; fractional identifiers are rejected. Source claim counts must\nalso be finite nonnegative integers.\n\nReconcile source claim counts with claim records, document the caps before\nfitting, and use exposure for frequency and pure premium but claim count for\nclaim-weighted severity.\n\n::: {#prepare-and-split .cell execution_count=3}\n``` {.python .cell-code}\ndata, claims, audit = load_mtpl2(n_samples=n_samples)\nsplits = make_splits(data)\nprint_frame(\"Target and weight definitions\", target_weight_table())\nstructural_audit = {\n    key: audit[key]\n    for key in (\n        \"policies\",\n        \"claim_cap\",\n        \"source_claims\",\n        \"claim_records\",\n        \"exposure_capped_rows\",\n        \"claim_count_mismatch_rows\",\n    )\n}\nprint_frame(\"Structural preparation audit (all source rows)\", pd.DataFrame([structural_audit]))\n```\n\n::: {#prepare-and-split-1 .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                  Target and weight definitions                   </span>\n┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model        </span>┃<span style=\"font-weight: bold\"> target      </span>┃<span style=\"font-weight: bold\"> weight   </span>┃<span style=\"font-weight: bold\"> family  </span>┃<span style=\"font-weight: bold\"> rows         </span>┃\n┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━╇━━━━━━━━━━━━━━┩\n│ frequency    │ Frequency   │ Exposure │ poisson │ all policies │\n│ severity     │ Severity    │ ClaimNb  │ gamma   │ claims only  │\n│ pure_premium │ PurePremium │ Exposure │ tweedie │ all policies │\n└──────────────┴─────────────┴──────────┴─────────┴──────────────┘\n</pre>\n```\n:::\n\n::: {#prepare-and-split-2 .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                              Structural preparation audit (all source rows)                               </span>\n┏━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> policies </span>┃<span style=\"font-weight: bold\"> claim_cap </span>┃<span style=\"font-weight: bold\"> source_claims </span>┃<span style=\"font-weight: bold\"> claim_records </span>┃<span style=\"font-weight: bold\"> exposure_capped_rows </span>┃<span style=\"font-weight: bold\"> claim_count_mismatch_rows </span>┃\n┡━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩\n│   678013 │   100,000 │         36102 │         26444 │                 1224 │                      9117 │\n└──────────┴───────────┴───────────────┴───────────────┴──────────────────────┴───────────────────────────┘\n</pre>\n```\n:::\n:::\n\n\n## Reserve a test set before making modelling choices\n\nTest performance is evidence only when test policies did not\ninfluence feature choices, Tweedie power, or LightGBM tuning.\n\nMake a fixed train/test split, then split training data into\ndevelopment-train and development-validation data.\n\nTune on development validation, refit once on all training\ndata, and inspect the untouched test set last. Also repeat by time or\ngeography to test stability.\n\n::: {#85852692 .cell execution_count=4}\n``` {.python .cell-code}\nprint_frame(\n    \"Split sizes\",\n    pd.DataFrame(\n        {\n            \"rows\": {\n                \"development train\": len(splits.development_train),\n                \"development validation\": len(splits.development_validation),\n                \"final train\": len(splits.train),\n                \"untouched test\": len(splits.test),\n            },\n            \"exposure\": {\n                \"development train\": splits.development_train[\"Exposure\"].sum(),\n                \"development validation\": splits.development_validation[\n                    \"Exposure\"\n                ].sum(),\n                \"final train\": splits.train[\"Exposure\"].sum(),\n                \"untouched test\": splits.test[\"Exposure\"].sum(),\n            },\n        }\n    ),\n)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                 Split sizes                  </span>\n┏━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> index                  </span>┃<span style=\"font-weight: bold\">   rows </span>┃<span style=\"font-weight: bold\"> exposure </span>┃\n┡━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━┩\n│ development train      │ 433928 │  229,446 │\n│ development validation │ 108482 │ 57,452.6 │\n│ final train            │ 542410 │  286,899 │\n│ untouched test         │ 135603 │ 71,461.5 │\n└────────────────────────┴────────┴──────────┘\n</pre>\n```\n:::\n:::\n\n\n### Training portfolio averages by hand\n\nThe structural audit above checks preparation across the source rows. Outcome\nsummaries and exploration below use training policies only. Each portfolio\naverage divides a total by the volume over which it was observed:\n\n- Frequency is total claim count divided by total exposure, or the\n  exposure-weighted mean of policy frequencies.\n- Severity is total capped claim amount divided by total claim count, or the\n  claim-count-weighted mean of severity among claim-bearing policies.\n- Pure premium is total capped claim amount divided by total exposure, or the\n  exposure-weighted mean of policy pure premiums.\n\nThe cell checks the frequency and pure-premium identities:\n\n::: {#fe399933 .cell execution_count=5}\n``` {.python .cell-code}\navg_frequency = splits.train[\"ClaimNb\"].sum() / splits.train[\"Exposure\"].sum()\navg_frequency_check = np.average(splits.train[\"Frequency\"], weights=splits.train[\"Exposure\"])\n\navg_pure_premium = splits.train[\"ClaimAmountCapped\"].sum() / splits.train[\"Exposure\"].sum()\navg_pure_premium_check = np.average(splits.train[\"PurePremium\"], weights=splits.train[\"Exposure\"])\n\nprint(f\"Average frequency:  {avg_frequency:.6f} claim / year\")\nprint(f\"  check (weighted mean of rate): {avg_frequency_check:.6f}\")\nprint(f\"Average pure premium: {avg_pure_premium:.2f} EUR / year\")\nprint(f\"  check (weighted mean of rate): {avg_pure_premium_check:.2f}\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAverage frequency:  0.073705 claim / year\n  check (weighted mean of rate): 0.073705\nAverage pure premium: 137.57 EUR / year\n  check (weighted mean of rate): 137.57\n```\n:::\n:::\n\n\nMultiplying a target by its weight recovers the policy's claim count for\nfrequency, or its capped claim amount for severity and pure premium.\n`portfolio_calibration_table` and `evaluate_predictions` use this identity\nto compare observed and predicted totals.\n\n::: {.callout-note collapse=\"true\"}\n## Look inside: `TARGET_SPECS` and `target_and_weight`\n\n`TARGET_SPECS` defines each component's target, weight, and eligible rows.\n`target_and_weight` looks up that definition and returns\n`(rows, target_array, weight_array)`. For severity, `claims_only=True` keeps\npolicies with `ClaimNb > 0`; frequency and pure premium use all policies.\n\n::: {#ae6c1daa .cell execution_count=6}\n``` {.python .cell-code}\nshow_source(target_and_weight)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef target_and_weight(\n    data: pd.DataFrame,\n    component: str,\n) -> tuple[pd.DataFrame, np.ndarray, np.ndarray]:\n    \"\"\"Return the rows, target, and weights for one pricing component.\"\"\"\n    spec = TARGET_SPECS[component]\n    rows = data.loc[data[\"ClaimNb\"] > 0] if spec.claims_only else data\n    return (\n        rows,\n        rows[spec.target].to_numpy(dtype=float),\n        rows[spec.weight].to_numpy(dtype=float),\n    )\n\n```\n:::\n:::\n\n\n:::\n\n## Explore uncapped training outcomes before fitting\n\nThese constant-mean references adapt the exploratory plots in the\n[GLUM motor tutorial](https://glum.readthedocs.io/en/latest/tutorials/glm_french_motor_tutorial/glm_french_motor.html).\nUse every training policy, accounting for unequal exposures and claim counts.\nSeverity here is uncapped; the capped modelling targets remain unchanged.\nTail disagreement can expose limitations of a reference. Pooled agreement\ncannot establish conditional model validity or select a model family.\nHere we estimate a shared portfolio mean and, for severity, Gamma dispersion.\nThe means do not vary with policy characteristics. The later\n[conditional diagnostics](#sec-conditional-diagnostics) repeat the comparison\nusing means predicted from those characteristics by the fitted GLUM models.\n\n### Frequency with unequal exposures\n\nThe constant annual rate $\\hat\\lambda$ is total claims divided by total exposure.\nCompare exposure-weighted count proportions with the same weighted mixture\nof Poisson distributions, each with mean $e_i\\hat\\lambda$, where $e_i$ is\npolicy $i$'s exposure in years. A Poisson at the\nannual rate alone would treat every policy as a full year. Keep zero claims\nand a final overflow bin, so both probability distributions sum to one.\nPooling policies with different exposures or risks can make the count\nvariance exceed the count mean, even if each policy follows a Poisson\ndistribution at its own mean. The later area residual-dispersion table\nchecks variation around fitted policy means.\n\n::: {#exploratory-frequency .cell execution_count=7}\n``` {.python .cell-code}\nexploration_train = splits.train\nexploration_exposure = exploration_train[\"Exposure\"].to_numpy(dtype=float)\nexploration_counts = exploration_train[\"ClaimNb\"].to_numpy(dtype=int)\nexploration_rate = exploration_counts.sum() / exploration_exposure.sum()\ncount_max = int(exploration_counts.max())\ncount_bins = np.arange(count_max + 2)\ncount_observed = np.bincount(\n    exploration_counts, weights=exploration_exposure, minlength=count_max + 2\n) / exploration_exposure.sum()\ncount_means = exploration_exposure * exploration_rate\ncount_reference = np.array([\n    np.average(poisson.pmf(k, count_means), weights=exploration_exposure)\n    for k in range(count_max + 1)\n] + [np.average(poisson.sf(count_max, count_means), weights=exploration_exposure)])\nprint(f\"All {len(exploration_train):,} training policies; annual rate={exploration_rate:.6f}\")\nprint_frame(\"Exposure-weighted count probabilities\", pd.DataFrame({\n    \"count\": [str(k) for k in range(count_max + 1)] + [f\">{count_max}\"],\n    \"observed\": count_observed, \"Poisson mixture\": count_reference,\n}))\nfig, axes = plt.subplots(1, 2, figsize=(11, 4))\nfor axis, log_y in zip(axes, (False, True)):\n    for values, label, color in (\n        (count_observed, \"Observed\", MODEL_COLORS[\"observed\"]),\n        (count_reference, \"Constant-rate Poisson mixture\", MODEL_COLORS[\"GLUM\"]),\n    ):\n        visible = values > 0 if log_y else np.ones(len(values), dtype=bool)\n        axis.plot(count_bins[visible], values[visible], \"o\", label=label, color=color)\n    axis.set_xticks(count_bins, [str(k) for k in range(count_max + 1)] + [f\">{count_max}\"])\n    axis.tick_params(axis=\"x\", labelrotation=45)\n    axis.set(xlabel=\"Policy claim count (last bin: overflow)\", ylabel=\"Exposure-weighted proportion\")\n    if log_y:\n        axis.set_yscale(\"log\")\n    axis.legend()\nfig.suptitle(f\"Constant-rate frequency reference: all {len(exploration_train):,} training policies\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAll 542,410 training policies; annual rate=0.073705\n```\n:::\n\n::: {#exploratory-frequency-1 .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">  Exposure-weighted count probabilities  </span>\n┏━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> count </span>┃<span style=\"font-weight: bold\">    observed </span>┃<span style=\"font-weight: bold\"> Poisson mixture </span>┃\n┡━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩\n│ 0     │    0.951939 │        0.944352 │\n│ 1     │   0.0454497 │       0.0538698 │\n│ 2     │  0.00248284 │      0.00173806 │\n│ 3     │ 0.000117393 │     3.93934e-05 │\n│ 4     │ 6.93625e-06 │      6.8803e-07 │\n│ 5     │ 2.78844e-07 │     9.76548e-09 │\n│ 6     │           0 │     1.16642e-10 │\n│ 7     │           0 │     1.20196e-12 │\n│ 8     │ 1.42908e-06 │     1.08864e-14 │\n│ 9     │ 2.78844e-07 │     8.79294e-17 │\n│ 10    │           0 │     6.40722e-19 │\n│ 11    │ 5.22833e-07 │     4.25215e-21 │\n│ 12    │           0 │     2.59047e-23 │\n│ 13    │           0 │     1.45841e-25 │\n│ 14    │           0 │     7.63116e-28 │\n│ 15    │           0 │      3.7296e-30 │\n│ 16    │ 1.15023e-06 │     1.70991e-32 │\n│ &gt;16   │           0 │     7.41233e-35 │\n└───────┴─────────────┴─────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/exploratory-frequency-output-3.png){#exploratory-frequency-2 width=1046 height=381}\n:::\n:::\n\n\nIn this full-data run, the 542,410 training policies have an annual claim rate\nof 0.073705. The observed exposure-weighted zero-count proportion is 0.95194,\nversus 0.94435 for the Poisson mixture. One-claim policies have less weight\nthan the reference predicts, while multiple claims have more. The linear\npanel is dominated by zeros; the log-y panel exposes the count-tail gaps.\n\n### Uncapped policy-average severity\n\nFor claim-bearing policies, let $n_i$ be policy $i$'s claim count and\n$y_i=\\text{ClaimAmountOriginal}_i/n_i$ its uncapped average claim amount.\nEstimate the mean $\\hat\\mu=\\sum_i n_i y_i/\\sum_i n_i$ and fit dispersion\n$\\phi$ with `fit_gamma_dispersion`, keeping that mean fixed.\n\nThe policy average becomes less variable as its claim count grows under\nthe Gamma assumption below. Both plotted distributions use claim-count weights.\n\n::: {.callout-note collapse=\"true\"}\n## Why claim count changes the Gamma reference\n\nUnder independent Gamma claims with a common mean $\\mu$ and dispersion\n$\\phi$, the policy average $y_i$ has shape $n_i/\\phi$, scale\n$\\phi\\mu/n_i$, and variance $\\phi\\mu^2/n_i$. We call $\\phi$ the base\ndispersion because it describes variation before division by claim count.\nEach policy contributes once to the fitting likelihood; its claim count\nalready enters through the shape and scale.\n:::\n\n::: {#exploratory-severity-reference .cell execution_count=8}\n``` {.python .cell-code}\nuncapped_severity_rows = splits.train.loc[splits.train[\"ClaimNb\"] > 0].copy()\nuncapped_severity_rows[\"UncappedSeverity\"] = (\n    uncapped_severity_rows[\"ClaimAmountOriginal\"] / uncapped_severity_rows[\"ClaimNb\"]\n)\nuncapped_y = uncapped_severity_rows[\"UncappedSeverity\"].to_numpy(dtype=float)\nuncapped_n = uncapped_severity_rows[\"ClaimNb\"].to_numpy(dtype=float)\nuncapped_mean = np.average(uncapped_y, weights=uncapped_n)\nuncapped_phi = fit_gamma_dispersion(\n    uncapped_y, np.full_like(uncapped_y, uncapped_mean), uncapped_n\n)\nmixture_counts, mixture_policies = np.unique(uncapped_n, return_counts=True)\nmixture_weights = mixture_counts * mixture_policies / uncapped_n.sum()\nseverity_grid = np.geomspace(uncapped_y.min(), uncapped_y.max(), 512)\nseverity_shape = mixture_counts / uncapped_phi\nseverity_scale = uncapped_phi * uncapped_mean / mixture_counts\nseverity_density = gamma.pdf(\n    severity_grid[:, None], a=severity_shape, scale=severity_scale\n) @ mixture_weights\nseverity_survival = gamma.sf(\n    severity_grid[:, None], a=severity_shape, scale=severity_scale\n) @ mixture_weights\nseverity_x, severity_empirical_sf = weighted_empirical_ccdf(uncapped_y, uncapped_n)\nprint(\n    f\"All {len(uncapped_y):,} claim-bearing training policies; {int(uncapped_n.sum()):,} claims; \"\n    f\"uncapped mean={uncapped_mean:,.2f} EUR; base phi={uncapped_phi:.6g}; \"\n    f\"maximum policy average={uncapped_y.max():,.2f} EUR\"\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAll 19,955 claim-bearing training policies; 21,146 claims; uncapped mean=2,346.72 EUR; base phi=1.54079; maximum policy average=4,075,400.56 EUR\n```\n:::\n:::\n\n\nThe histogram uses logarithmic amount bins with density per euro.\nThe survival function (SF), $P(Y>x)$, gives the probability of exceeding\namount $x$. Both curves keep the full claim-count denominator and extend\nto the observed maximum.\n\n::: {#cell-exploratory-severity-density .cell execution_count=9}\n``` {.python .cell-code}\nseverity_bins = np.geomspace(uncapped_y.min(), uncapped_y.max(), 41)\nfig, axis = plt.subplots(figsize=(7, 4.5))\naxis.hist(uncapped_y, bins=severity_bins, weights=uncapped_n, density=True,\n          alpha=0.35, color=MODEL_COLORS[\"observed\"], label=\"Observed (claim weighted)\")\naxis.plot(severity_grid, severity_density, color=MODEL_COLORS[\"GLUM\"], label=\"Constant-mean Gamma mixture\")\naxis.set(xscale=\"log\", xlabel=\"Uncapped policy-average severity (EUR)\",\n         ylabel=\"Density per EUR\", title=f\"All {len(uncapped_y):,} claim-bearing training policies\")\naxis.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/exploratory-severity-density-output-1.png){#exploratory-severity-density width=662 height=420}\n:::\n:::\n\n\n::: {#cell-exploratory-severity-survival .cell execution_count=10}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(11, 4.5))\nfor axis, log_x in zip(axes, (False, True)):\n    axis.stairs(severity_empirical_sf[:-1], severity_x, baseline=None,\n                color=MODEL_COLORS[\"observed\"], label=\"Observed (claim weighted)\")\n    visible = severity_survival > 0\n    axis.plot(severity_grid[visible], severity_survival[visible],\n              color=MODEL_COLORS[\"GLUM\"], label=\"Constant-mean Gamma mixture\")\n    axis.set(yscale=\"log\", xlim=(uncapped_y.min() if log_x else 0, uncapped_y.max()),\n             xlabel=\"Uncapped policy-average severity (EUR)\", ylabel=\"SF: P(policy average > x)\")\n    axis.set_ylim(bottom=severity_empirical_sf[severity_empirical_sf > 0].min() / 100, top=1.05)\n    if log_x:\n        axis.set_xscale(\"log\")\n    axis.legend()\nfig.suptitle(f\"Uncapped severity: all {len(uncapped_y):,} claim-bearing training policies\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/exploratory-severity-survival-output-1.png){#exploratory-severity-survival width=1045 height=426}\n:::\n:::\n\n\nThe 19,955 claim-bearing policies represent 21,146 claims. Their uncapped\nclaim-weighted mean is EUR 2,346.72, with fitted base dispersion 1.54079.\nThe density histogram has concentrations that the smooth Gamma mixture does\nnot reproduce. At EUR 10,000 the reference survival is higher than observed;\nat EUR 100,000 and EUR 1,000,000 it is far lower, as the table below shows.\nThe maximum policy average is EUR 4,075,400.56. Thus this constant-mean Gamma\nreference understates the far upper tail, but does not understate survival\nat every threshold. The next plot shows individual claims, with equal weight per claim.\n\n::: {#cell-exploratory-tail-probabilities .cell execution_count=11}\n``` {.python .cell-code}\ntail_thresholds = np.array([10_000, 100_000, 1_000_000])\nprint_frame(\"Uncapped policy-average severity survival (full claim-weight denominator)\", pd.DataFrame({\n    \"threshold_EUR\": tail_thresholds,\n    \"observed_SF\": [uncapped_n[uncapped_y > x].sum() / uncapped_n.sum() for x in tail_thresholds],\n    \"Gamma_mixture_SF\": gamma.sf(tail_thresholds[:, None], a=severity_shape, scale=severity_scale) @ mixture_weights,\n}))\n```\n\n::: {#exploratory-tail-probabilities .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\"> Uncapped policy-average severity survival (full  </span>\n<span style=\"font-style: italic\">            claim-weight denominator)             </span>\n┏━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> threshold_EUR </span>┃<span style=\"font-weight: bold\"> observed_SF </span>┃<span style=\"font-weight: bold\"> Gamma_mixture_SF </span>┃\n┡━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩\n│         10000 │   0.0173555 │        0.0265315 │\n│        100000 │   0.0019389 │      1.93296e-13 │\n│       1000000 │ 9.45805e-05 │     6.92895e-122 │\n└───────────────┴─────────────┴──────────────────┘\n</pre>\n```\n:::\n:::\n\n\n### Uncapped individual claims: a separate descriptive view\n\nRetain all positive claim records belonging to training policy IDs. Each claim\nhas equal weight. This uncapped, per-claim survival curve describes the raw\nloss tail; it is a different observable from policy-average severity.\nThere is no fitted Gamma or Tweedie reference in this view.\n\n::: {#cell-uncapped-training-claims .cell execution_count=12}\n``` {.python .cell-code}\ntraining_claims = claims.loc[claims[\"IDpol\"].isin(splits.train.index)]\nclaim_amounts = training_claims[\"ClaimAmount\"].to_numpy(dtype=float)\nclaim_x, claim_sf = weighted_empirical_ccdf(claim_amounts, np.ones(len(claim_amounts)))\nfig, axis = plt.subplots(figsize=(6.5, 4.5))\naxis.stairs(claim_sf[:-1], claim_x, baseline=None, color=MODEL_COLORS[\"observed\"])\naxis.set(xscale=\"log\", yscale=\"log\", xlim=(claim_x.min(), claim_x.max()), xlabel=\"Uncapped individual claim (EUR)\", ylabel=\"SF: P(claim > x)\", title=f\"Descriptive training claim tail (n={len(training_claims):,} claims)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/uncapped-training-claims-output-1.png){#uncapped-training-claims width=613 height=420}\n:::\n:::\n\n\n### Grouped severity mean and variance\n\nWe next check how severity variation changes across vehicle-power and\nbonus-malus groups. The reference below uses the Gamma relationship between\nmean and variance; it does not estimate a new variance power from the groups.\n\nWithin each `VehPower` or `BonusMalus` group, let $m_g$ be the number of\nclaim-bearing policies and $n_i$ the policy claim count. The claim-weighted\nmean $\\bar y_g$ and the measure of variation $V_g$ are\n\n$$\n\\bar y_g=\\frac{\\sum_i n_i y_i}{\\sum_i n_i},\\qquad\nV_g=\\frac{\\sum_i n_i(y_i-\\bar y_g)^2}{m_g-1}.\n$$\n\nUnder a common within-group Gamma mean, $V_g$ estimates $\\phi\\mu_g^2$.\nHere $\\mu_g$ is that group's common mean. The denominator counts policies\nminus one; the ordinary weighted variance would divide by total claim count.\nRetain groups with at least four claims and two claim-bearing policies.\nThe table reports counts and exclusion reasons, including zero variance.\n\n::: {#exploratory-severity-groups .cell execution_count=13}\n``` {.python .cell-code}\nseverity_group_tables = {}\nfig, axes = plt.subplots(1, 2, figsize=(11, 4.5))\nfor by, axis in zip((\"VehPower\", \"BonusMalus\"), axes):\n    grouped = uncapped_severity_rows.groupby(by, observed=True)\n    table = grouped.agg(\n        policies=(\"ClaimNb\", \"size\"), claims=(\"ClaimNb\", \"sum\"),\n        amount=(\"ClaimAmountOriginal\", \"sum\"),\n    )\n    table[\"mean\"] = table[\"amount\"] / table[\"claims\"]\n    policy_means = grouped[\"ClaimAmountOriginal\"].transform(\"sum\") / grouped[\"ClaimNb\"].transform(\"sum\")\n    residual_squares = uncapped_severity_rows[\"ClaimNb\"] * (\n        uncapped_severity_rows[\"UncappedSeverity\"] - policy_means\n    ) ** 2\n    table[\"V\"] = residual_squares.groupby(uncapped_severity_rows[by], observed=True).sum() / (\n        table[\"policies\"] - 1\n    ).replace(0, np.nan)\n    table[\"status\"] = \"included\"\n    sparse = (table[\"claims\"] < 4) | (table[\"policies\"] < 2)\n    table.loc[~sparse & (table[\"V\"] == 0), \"status\"] = \"zero variance: excluded from logs\"\n    table.loc[sparse, \"status\"] = \"sparse: excluded\"\n    severity_group_tables[by] = table.drop(columns=\"amount\")\n    print_frame(f\"Uncapped severity by {by} (all observed claim-bearing groups)\", severity_group_tables[by])\n    print(f\"{by}: {int(sparse.sum())} sparse groups; {int((~sparse & (table['V'] == 0)).sum())} retained zero-variance groups.\")\n    valid = table.loc[table[\"status\"] == \"included\"]\n    if valid.empty:\n        axis.set_title(by)\n        axis.text(0.5, 0.5, \"No groups eligible for logarithmic display\", ha=\"center\", transform=axis.transAxes)\n        axis.set_axis_off()\n        continue\n    axis.scatter(valid[\"mean\"], valid[\"V\"], color=MODEL_COLORS[\"observed\"], label=\"Observed groups\")\n    mean_grid = np.geomspace(valid[\"mean\"].min(), valid[\"mean\"].max(), 128)\n    axis.plot(mean_grid, uncapped_phi * mean_grid**2, color=MODEL_COLORS[\"GLUM\"], label=r\"Gamma: $\\hat\\phi\\,\\bar y^2$\")\n    axis.set(xscale=\"log\", yscale=\"log\", xlabel=\"Claim-weighted uncapped mean (EUR)\",\n             ylabel=r\"$V_g$ (EUR$^2$)\", title=by)\n    axis.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {#exploratory-severity-groups-1 .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\"> Uncapped severity by VehPower (all observed claim-bearing groups)  </span>\n┏━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> VehPower </span>┃<span style=\"font-weight: bold\"> policies </span>┃<span style=\"font-weight: bold\"> claims </span>┃<span style=\"font-weight: bold\">     mean </span>┃<span style=\"font-weight: bold\">           V </span>┃<span style=\"font-weight: bold\"> status   </span>┃\n┡━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━┩\n│ 10       │      909 │    976 │  2,229.1 │  1.2419e+08 │ included │\n│ 11       │      513 │    553 │  1,805.5 │ 3.22743e+07 │ included │\n│ 12       │      216 │    228 │ 2,666.54 │ 8.19911e+07 │ included │\n│ 13       │      105 │    110 │  1,478.5 │ 1.89543e+06 │ included │\n│ 14       │       69 │     75 │ 1,189.45 │ 1.04903e+06 │ included │\n│ 15       │       80 │     82 │ 1,332.45 │ 2.30918e+06 │ included │\n│ 4        │     2962 │   3195 │ 2,453.73 │ 6.52719e+08 │ included │\n│ 5        │     3916 │   4135 │ 1,701.73 │  2.5394e+07 │ included │\n│ 6        │     4737 │   5005 │ 2,404.83 │ 3.06644e+08 │ included │\n│ 7        │     4264 │   4478 │ 2,313.45 │ 2.47129e+08 │ included │\n│ 8        │     1251 │   1319 │ 1,750.43 │  2.2213e+07 │ included │\n│ 9        │      933 │    990 │ 5,959.24 │ 1.78143e+10 │ included │\n└──────────┴──────────┴────────┴──────────┴─────────────┴──────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nVehPower: 0 sparse groups; 0 retained zero-variance groups.\n```\n:::\n\n::: {#exploratory-severity-groups-2 .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">              Uncapped severity by BonusMalus (all observed claim-bearing groups)              </span>\n┏━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> BonusMalus </span>┃<span style=\"font-weight: bold\"> policies </span>┃<span style=\"font-weight: bold\"> claims </span>┃<span style=\"font-weight: bold\">     mean </span>┃<span style=\"font-weight: bold\">           V </span>┃<span style=\"font-weight: bold\"> status                            </span>┃\n┡━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩\n│         50 │     8794 │   9229 │ 1,956.23 │  7.6735e+07 │ included                          │\n│         51 │      328 │    341 │ 2,472.87 │ 1.95345e+08 │ included                          │\n│         52 │      186 │    199 │ 1,550.32 │ 5.36977e+06 │ included                          │\n│         53 │      120 │    128 │  1,329.2 │ 1.90647e+06 │ included                          │\n│         54 │      346 │    362 │  2,636.5 │ 2.41011e+08 │ included                          │\n│         55 │      261 │    269 │ 2,484.24 │ 1.37259e+08 │ included                          │\n│         56 │      168 │    178 │ 1,815.72 │ 2.09432e+07 │ included                          │\n│         57 │      372 │    395 │ 1,651.36 │ 1.42206e+07 │ included                          │\n│         58 │      415 │    437 │  1,596.5 │ 8.94004e+06 │ included                          │\n│         59 │      104 │    108 │ 1,727.21 │ 4.72674e+06 │ included                          │\n│         60 │      415 │    434 │ 1,481.09 │  4.4718e+06 │ included                          │\n│         61 │       68 │     73 │ 1,501.93 │ 2.01603e+06 │ included                          │\n│         62 │      786 │    845 │ 1,769.58 │ 1.17036e+07 │ included                          │\n│         63 │      209 │    217 │ 5,032.62 │  2.8619e+09 │ included                          │\n│         64 │      395 │    415 │ 1,449.02 │ 3.53611e+06 │ included                          │\n│         65 │       94 │     98 │ 1,465.26 │ 1.53306e+06 │ included                          │\n│         66 │       54 │     57 │    1,143 │     832,273 │ included                          │\n│         67 │      183 │    190 │ 1,502.53 │ 3.74769e+06 │ included                          │\n│         68 │      439 │    466 │ 1,974.94 │ 1.00805e+08 │ included                          │\n│         69 │       58 │     66 │ 1,294.83 │ 1.01024e+06 │ included                          │\n│         70 │       63 │     66 │    1,920 │ 9.99669e+06 │ included                          │\n│         71 │      161 │    167 │ 2,684.02 │ 1.55163e+08 │ included                          │\n│         72 │      502 │    534 │  2,561.8 │ 1.75246e+08 │ included                          │\n│         73 │       70 │     77 │  1,361.6 │     808,076 │ included                          │\n│         74 │       40 │     42 │ 1,166.49 │ 1.19012e+06 │ included                          │\n│         75 │      101 │    108 │ 2,120.07 │ 3.80861e+07 │ included                          │\n│         76 │      502 │    531 │  2,490.4 │ 7.04788e+07 │ included                          │\n│         77 │      124 │    145 │ 1,496.07 │ 3.72321e+06 │ included                          │\n│         78 │       63 │     66 │ 1,698.33 │ 3.24168e+06 │ included                          │\n│         79 │       10 │     10 │ 1,492.28 │ 1.86202e+06 │ included                          │\n│         80 │      546 │    577 │ 1,905.94 │ 6.62327e+07 │ included                          │\n│         81 │       30 │     32 │ 1,575.23 │ 3.35452e+06 │ included                          │\n│         82 │       28 │     29 │ 1,513.31 │ 3.47771e+06 │ included                          │\n│         83 │       39 │     42 │ 1,324.59 │ 1.86128e+06 │ included                          │\n│         84 │       11 │     11 │ 1,447.37 │ 1.37452e+06 │ included                          │\n│         85 │      565 │    591 │  1,909.9 │ 4.60821e+07 │ included                          │\n│         86 │       21 │     23 │ 1,180.34 │     545,756 │ included                          │\n│         87 │        6 │      6 │ 1,451.12 │     592,807 │ included                          │\n│         88 │       36 │     40 │ 1,309.19 │     442,982 │ included                          │\n│         89 │        4 │      4 │   890.36 │     121,289 │ included                          │\n│         90 │      556 │    588 │ 2,801.17 │ 3.08522e+08 │ included                          │\n│         91 │       16 │     18 │ 1,203.04 │     310,193 │ included                          │\n│         92 │        8 │     10 │ 1,085.03 │    40,146.5 │ included                          │\n│         93 │       13 │     18 │ 2,371.95 │ 5.58605e+07 │ included                          │\n│         94 │        1 │      1 │  1,150.9 │           — │ sparse: excluded                  │\n│         95 │      703 │    756 │ 1,928.82 │ 1.96509e+07 │ included                          │\n│         96 │       21 │     27 │ 1,430.43 │ 1.94497e+06 │ included                          │\n│         97 │       13 │     15 │ 3,434.56 │ 2.80413e+07 │ included                          │\n│         98 │        3 │      3 │  846.583 │     383,240 │ sparse: excluded                  │\n│         99 │        3 │      3 │ 2,787.09 │ 3.32175e+06 │ sparse: excluded                  │\n│        100 │      989 │   1091 │ 8,646.19 │ 1.95385e+10 │ included                          │\n│        101 │       16 │     18 │  883.257 │     207,380 │ included                          │\n│        102 │        8 │     11 │  1,204.1 │     388,946 │ included                          │\n│        103 │        4 │      4 │ 1,809.91 │     646,887 │ included                          │\n│        104 │        2 │      2 │  787.115 │     232,569 │ sparse: excluded                  │\n│        105 │        5 │      7 │ 1,612.71 │ 1.23131e+06 │ included                          │\n│        106 │      156 │    166 │ 2,326.28 │ 1.15379e+08 │ included                          │\n│        107 │        3 │      4 │ 1,128.12 │           0 │ zero variance: excluded from logs │\n│        108 │        2 │      3 │  764.237 │     198,617 │ sparse: excluded                  │\n│        110 │        4 │      5 │ 2,751.81 │ 7.17422e+06 │ included                          │\n│        112 │      190 │    205 │ 2,144.01 │ 3.72302e+07 │ included                          │\n│        113 │        1 │      1 │    1,204 │           — │ sparse: excluded                  │\n│        114 │        2 │      2 │ 1,671.39 │     268,395 │ sparse: excluded                  │\n│        115 │        6 │      6 │ 1,351.95 │     962,331 │ included                          │\n│        116 │        2 │      2 │ 1,128.12 │           0 │ sparse: excluded                  │\n│        117 │        1 │      1 │ 1,128.12 │           — │ sparse: excluded                  │\n│        118 │      186 │    199 │ 1,762.47 │ 1.17676e+07 │ included                          │\n│        119 │        1 │      1 │    95.26 │           — │ sparse: excluded                  │\n│        121 │        2 │      3 │    1,204 │           0 │ sparse: excluded                  │\n│        122 │        1 │      1 │ 1,015.35 │           — │ sparse: excluded                  │\n│        125 │      214 │    236 │ 1,549.52 │ 3.95742e+06 │ included                          │\n│        126 │        1 │      1 │      602 │           — │ sparse: excluded                  │\n│        130 │        1 │      1 │    1,204 │           — │ sparse: excluded                  │\n│        132 │       10 │     14 │ 1,742.05 │ 5.21181e+06 │ included                          │\n│        133 │        6 │      7 │ 1,253.79 │     830,237 │ included                          │\n│        138 │        1 │      1 │ 1,128.12 │           — │ sparse: excluded                  │\n│        139 │        8 │      8 │ 1,011.46 │     225,615 │ included                          │\n│        140 │       14 │     18 │ 13,067.6 │ 1.46845e+09 │ included                          │\n│        147 │       20 │     24 │ 3,567.05 │ 6.31856e+07 │ included                          │\n│        148 │       11 │     12 │ 1,004.64 │      54,851 │ included                          │\n│        156 │       19 │     28 │ 3,500.44 │ 5.27964e+07 │ included                          │\n│        158 │        3 │      3 │  776.393 │     419,362 │ sparse: excluded                  │\n│        165 │        1 │      1 │ 1,423.73 │           — │ sparse: excluded                  │\n│        173 │        4 │      4 │ 1,083.78 │    29,364.8 │ included                          │\n│        176 │        1 │      1 │    1,172 │           — │ sparse: excluded                  │\n│        187 │        2 │      2 │ 3,274.99 │ 9.21909e+06 │ sparse: excluded                  │\n│        190 │        1 │      2 │    1,330 │           — │ sparse: excluded                  │\n│        196 │        1 │      2 │  915.425 │           — │ sparse: excluded                  │\n│        208 │        1 │      1 │    1,128 │           — │ sparse: excluded                  │\n│        228 │        1 │      1 │ 1,128.12 │           — │ sparse: excluded                  │\n└────────────┴──────────┴────────┴──────────┴─────────────┴───────────────────────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nBonusMalus: 23 sparse groups; 1 retained zero-variance groups.\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/exploratory-severity-groups-output-5.png){#exploratory-severity-groups-3 width=1043 height=420}\n:::\n:::\n\n\nThe grouped points are descriptive. Sparse groups, large losses, and\nwithin-group risk differences affect their relation to the fixed Gamma\n$p=2$ reference. Later conditional diagnostics check residual dispersion\naround fitted risk-specific means on the capped modelling targets.\n\nAll 12 vehicle-power groups pass the count thresholds and have positive\nvariance. For `BonusMalus`, 23 groups fail the count thresholds and one\nretained group has zero variance. The scatter is broad, with several\nhigh-mean, high-variance groups above the fixed Gamma reference; this\naggregation does not identify a conditional variance law or select the\nTweedie power used next.\n\n## Select the Tweedie variance power on development data\n\nDirect pure-premium models need a variance power between Poisson and\nGamma. Selecting it on the test set would make the final comparison optimistic.\n\nFor each candidate power, fit a GLUM mean model to development-training\nrates with exposure weights. Keep those predicted means fixed and estimate\nbase dispersion $\\phi$ on that training fit. Score development-validation\nrows with the same $\\phi$, retain the power with the largest validation\nlikelihood, and use that one power for every later deviance comparison.\n\nRetain the candidate-power profile for review.\n\n::: {#24f492d1 .cell execution_count=14}\n``` {.python .cell-code}\nselected_power, power_profile = select_tweedie_power(\n    splits.development_train,\n    splits.development_validation,\n)\nprint_frame(\"Tweedie power profile\", power_profile)\nprint(f\"Selected Tweedie power: {selected_power:.1f}\")\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                   Tweedie power profile                   </span>\n┏━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> power </span>┃<span style=\"font-weight: bold\"> training_dispersion </span>┃<span style=\"font-weight: bold\"> validation_log_likelihood </span>┃\n┡━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━┩\n│   1.1 │            1,014.47 │                 -63,511.1 │\n│   1.2 │             804.293 │                 -56,672.9 │\n│   1.3 │             588.712 │                 -54,232.5 │\n│   1.4 │             425.673 │                 -53,224.6 │\n│   1.5 │             313.203 │                 -52,917.9 │\n│   1.6 │             239.604 │                 -53,060.9 │\n│   1.7 │             195.846 │                   -53,595 │\n│   1.8 │             180.561 │                 -54,633.8 │\n│   1.9 │             222.467 │                 -56,755.3 │\n└───────┴─────────────────────┴───────────────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nSelected Tweedie power: 1.5\n```\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Look inside: Tweedie power selection\n\nWe score how much probability each candidate assigns to the validation\noutcomes. Below, $f_p$ is the Tweedie density for positive rates and its\nprobability mass for zero. The mean $\\hat\\mu_i$ comes from the fitted\nmodel; $e_i$ is exposure and $\\phi$ is base dispersion.\nThe validation log likelihood is\n\n$$\nL(p,\\phi)=\\sum_i \\log f_p(y_i;\\hat\\mu_i,\\phi/e_i),\n\\qquad y_i=\\frac{\\text{ClaimAmountCapped}_i}{e_i}.\n$$\n\n`fit_tweedie_dispersion` optimizes $\\log\\phi$. The Pearson estimate\n$\\frac{1}{n}\\sum_i e_i(y_i-\\hat\\mu_i)^2/\\hat\\mu_i^p$ supplies only the\nstarting value; a failed optimization raises.\n\n`tweedie_log_likelihood` uses [GLUM's scalar-dispersion density API](https://glum.readthedocs.io/en/latest/glm.html#glum.TweedieDistribution.log_likelihood)\nwith $a_i=e_i^{1/(2-p)}$, transformed observations $a_i y_i$, transformed\nmeans $a_i\\hat\\mu_i$, and unit likelihood weights. It adds the Jacobian\n$\\sum_{y_i>0}\\log a_i$ for positive rates. Zero claims retain their\nprobability mass, with no Jacobian term. Targets and weights follow the\n[GLUM motor tutorial](https://glum.readthedocs.io/en/latest/tutorials/glm_french_motor_tutorial/glm_french_motor.html).\n\n::: {#19a928b8 .cell execution_count=15}\n``` {.python .cell-code}\nshow_source(select_tweedie_power)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef select_tweedie_power(\n    development_train: pd.DataFrame,\n    development_validation: pd.DataFrame,\n    powers: tuple[float, ...] = TWEEDIE_POWERS,\n) -> tuple[float, pd.DataFrame]:\n    \"\"\"Select p by validation profile likelihood under the fitted rate convention.\"\"\"\n    train_rows, y_train, w_train = target_and_weight(development_train, \"pure_premium\")\n    validation_rows, y_validation, w_validation = target_and_weight(\n        development_validation, \"pure_premium\"\n    )\n    results = []\n    for power in powers:\n        family = TweedieDistribution(power)\n        model = GeneralizedLinearRegressor(\n            family=family,\n            link=\"log\",\n            formula=RATING_FORMULA,\n            drop_first=True,\n            alpha=0,\n            max_iter=200,\n        ).fit(train_rows, y_train, sample_weight=w_train)\n        train_prediction = model.predict(train_rows)\n        validation_prediction = model.predict(validation_rows)\n        dispersion = fit_tweedie_dispersion(y_train, train_prediction, w_train, power)\n        log_likelihood = tweedie_log_likelihood(\n            y_validation, validation_prediction, w_validation, power, dispersion\n        )\n        results.append(\n            {\n                \"power\": power,\n                \"training_dispersion\": dispersion,\n                \"validation_log_likelihood\": log_likelihood,\n            }\n        )\n    profile = pd.DataFrame(results)\n    if not np.isfinite(profile[\"validation_log_likelihood\"]).all():\n        raise RuntimeError(\"Tweedie profile likelihood produced non-finite values\")\n    selected = float(\n        profile.loc[profile[\"validation_log_likelihood\"].idxmax(), \"power\"]\n    )\n    return selected, profile\n\n```\n:::\n:::\n\n\n:::\n\n## Fit an interpretable GLUM benchmark {#sec-glum-benchmark}\n\nThe GLUM benchmark lets us judge whether a flexible model earns its extra\ncomplexity. Fit a regularized model, which penalizes coefficient size, for\nprediction. Fit a separate unregularized model for coefficient intervals,\ncategorical relativities (multiplicative effects on the predicted rate), and sandwich standard\nerrors, which allow the variance to differ from the working distribution.\n\nFor each categorical term, the relativity compares that level with the\nomitted reference level while holding other predictors fixed. The intercept,\ncontinuous terms, and individual spline coefficients keep their coefficient\nintervals but have blank relativity cells. Comparing two ages requires\ncombining all spline coefficients with the difference between the spline\nbasis values at those ages, then exponentiating that combined log-rate change.\nAn individual spline coefficient is not an age relativity.\n\nThe table recognizes main-effect treatment terms named `C(<feature>)[...]`\nfor `VehBrand`, `VehPower`, `VehGas`, `Region`, and `Area`. This rule must be\nreviewed if the formula adds interactions or uses different contrast coding.\n\nThe unregularized model's confidence intervals describe that fit. They do\nnot apply to the penalized predictive fit. Review relativities for\nplausibility and choose predictions using out-of-sample evidence.\n\nExposure and claim count determine each policy's weight in fitting. The\nstandard-error calculation also needs the number of independent policy rows.\nGLUM 3.4.1 uses total weight in its small-sample adjustment, so we calculate\ncovariance with a copy of the weights rescaled to average one. This preserves\ntheir relative values and the fitted means, while making the adjustment use\nthe number of policy rows. Original exposures and claim counts still define\nthe targets, totals, and distribution parameters.\n\nThis inference assumes independence between policy rows. We set dispersion\nto one only for the sandwich calculation: its common scalar cancels between\nthe information matrix and score contributions. The fitted distribution\ndispersions remain separate.\n\n`fit_glum_predictive` uses 3-fold cross-validation to compare penalty\nstrengths $\\alpha$ and penalty mixtures $\\mathrm{l1\\_ratio}$ (0 for ridge,\n1 for lasso). For severity, it appends zero-weight\nanchor rows so categories absent in the training data still receive a\ndefined prediction.\n\n::: {.callout-note collapse=\"true\"}\n## Look inside: `RATING_FORMULA`\n\n```\nC(VehBrand) + C(VehPower) + C(VehGas) + C(Region) + C(Area)\n + bs(VehAge, df=5, lower_bound=0, upper_bound=100)\n + bs(DrivAge, df=5, lower_bound=18, upper_bound=100)\n + bs(BonusMalus, knots=[55, 65, 80, 100], lower_bound=0, upper_bound=230)\n + LogDensity\n```\n:::\n\nFor the full implementation see\n[`src/nonlife_pureprem/pure_premium.py`](https://github.com/ThomasBury/nonlife-pureprem/blob/main/src/nonlife_pureprem/pure_premium.py)\n(`fit_glum_predictive`, `fit_glum_inference`).\n\n::: {#9ce70de6 .cell execution_count=16}\n``` {.python .cell-code}\nglum_models = {}\nfor component in TARGET_SPECS:\n    glum_models[component] = fit_glum_predictive(\n        splits.train,\n        component,\n        selected_power,\n        n_alphas=n_alphas,\n    )\n    inference = fit_glum_inference(splits.train, component, selected_power)\n    relativities = coefficient_relativity_table(inference)\n    print_frame(f\"GLUM {component} relativities\", relativities)\n    print(\n        f\"GLUM {component}: alpha={glum_models[component].alpha_:.6g}, \"\n        f\"l1_ratio={glum_models[component].l1_ratio_:.1f}\"\n    )\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                                            GLUM frequency relativities                                            </span>\n┏━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> term       </span>┃<span style=\"font-weight: bold\">       coef </span>┃<span style=\"font-weight: bold\"> std_error </span>┃<span style=\"font-weight: bold\">    p_value </span>┃<span style=\"font-weight: bold\">   ci_lower </span>┃<span style=\"font-weight: bold\">   ci_upper </span>┃<span style=\"font-weight: bold\"> relativi… </span>┃<span style=\"font-weight: bold\"> relativit… </span>┃<span style=\"font-weight: bold\"> relativi… </span>┃\n┡━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━┩\n│ intercept  │    48.5922 │   143.259 │   0.734465 │    -232.19 │    329.374 │         — │          — │         — │\n│ C(VehBran… │ -0.0172732 │ 0.0458957 │   0.706651 │  -0.107227 │  0.0726807 │  0.982875 │   0.898322 │   1.07539 │\n│ C(VehBran… │   0.194105 │ 0.0479421 │ 5.14932e-… │    0.10014 │    0.28807 │   1.21422 │    1.10533 │   1.33385 │\n│ C(VehBran… │  -0.287749 │   0.02773 │          0 │  -0.342099 │  -0.233399 │   0.74995 │   0.710278 │  0.791838 │\n│ C(VehBran… │  0.0337866 │ 0.0510953 │   0.508454 │ -0.0663584 │   0.133932 │   1.03436 │   0.935795 │   1.14331 │\n│ C(VehBran… │  -0.229152 │  0.100983 │  0.0232547 │  -0.427075 │ -0.0312299 │  0.795207 │   0.652415 │  0.969253 │\n│ C(VehBran… │ -0.0102763 │ 0.0199964 │   0.607317 │ -0.0494686 │   0.028916 │  0.989776 │   0.951735 │   1.02934 │\n│ C(VehBran… │  0.0492379 │ 0.0273491 │  0.0718062 │ -0.004365… │   0.102841 │   1.05047 │   0.995644 │   1.10832 │\n│ C(VehBran… │ 0.00503316 │ 0.0375081 │   0.893253 │ -0.0684813 │  0.0785477 │   1.00505 │   0.933811 │   1.08171 │\n│ C(VehBran… │  0.0754645 │ 0.0314607 │  0.0164539 │  0.0138026 │   0.137126 │   1.07838 │     1.0139 │   1.14697 │\n│ C(VehBran… │ 0.00254263 │ 0.0357887 │   0.943361 │ -0.0676019 │  0.0726871 │   1.00255 │   0.934633 │   1.07539 │\n│ C(VehPowe… │  0.0646299 │ 0.0556674 │   0.245641 │ -0.0444761 │   0.173736 │   1.06676 │   0.956498 │   1.18974 │\n│ C(VehPowe… │  0.0044405 │  0.076405 │   0.953655 │  -0.145311 │   0.154191 │   1.00445 │   0.864754 │   1.16671 │\n│ C(VehPowe… │ 0.0004291… │  0.103373 │   0.996688 │  -0.202178 │   0.203036 │   1.00043 │    0.81695 │   1.22512 │\n│ C(VehPowe… │ -0.004052… │   0.12528 │   0.974195 │  -0.249596 │   0.241491 │  0.995956 │   0.779115 │   1.27315 │\n│ C(VehPowe… │  0.0843423 │  0.116134 │   0.467684 │  -0.143275 │    0.31196 │     1.088 │   0.866516 │    1.3661 │\n│ C(VehPowe… │  -0.218744 │ 0.0394682 │ 2.98548e-… │    -0.2961 │  -0.141388 │  0.803527 │   0.743713 │  0.868153 │\n│ C(VehPowe… │  -0.168115 │  0.037524 │ 7.45786e-… │   -0.24166 │ -0.0945688 │  0.845257 │   0.785323 │  0.909765 │\n│ C(VehPowe… │  -0.148804 │  0.037054 │ 5.92285e-… │  -0.221429 │ -0.0761794 │  0.861738 │   0.801373 │   0.92665 │\n│ C(VehPowe… │  -0.149607 │ 0.0368592 │ 4.93099e-… │   -0.22185 │ -0.0773642 │  0.861046 │   0.801036 │  0.925553 │\n│ C(VehPowe… │  -0.123003 │ 0.0436259 │ 0.00481008 │  -0.208508 │ -0.0374974 │  0.884261 │   0.811795 │  0.963197 │\n│ C(VehPowe… │ 0.00761889 │    0.0468 │   0.870679 │ -0.0841075 │  0.0993453 │   1.00765 │   0.919332 │   1.10445 │\n│ C(VehGas)… │   -0.15319 │ 0.0154094 │          0 │  -0.183392 │  -0.122988 │  0.857967 │   0.832442 │  0.884274 │\n│ C(Region)… │   0.019145 │  0.139134 │   0.890556 │  -0.253553 │   0.291843 │   1.01933 │   0.776038 │   1.33889 │\n│ C(Region)… │   0.173236 │  0.068149 │  0.0110213 │  0.0396668 │   0.306806 │   1.18915 │    1.04046 │   1.35908 │\n│ C(Region)… │ -0.0760519 │  0.084883 │   0.370273 │   -0.24242 │  0.0903158 │  0.926768 │   0.784727 │   1.09452 │\n│ C(Region)… │  0.0207908 │ 0.0347074 │   0.549153 │ -0.0472345 │   0.088816 │   1.02101 │   0.953864 │   1.09288 │\n│ C(Region)… │ 0.00238309 │ 0.0605141 │   0.968587 │  -0.116222 │   0.120989 │   1.00239 │   0.890277 │   1.12861 │\n│ C(Region)… │ -0.0139426 │ 0.0697151 │   0.841485 │  -0.150582 │   0.122697 │  0.986154 │   0.860207 │   1.13054 │\n│ C(Region)… │  0.0553533 │ 0.0479022 │   0.247866 │ -0.0385333 │    0.14924 │   1.05691 │     0.9622 │   1.16095 │\n│ C(Region)… │  -0.126668 │  0.061443 │    0.03925 │  -0.247094 │ -0.006242… │  0.881026 │   0.781067 │  0.993777 │\n│ C(Region)… │  0.0367246 │  0.123093 │   0.765437 │  -0.204533 │   0.277982 │   1.03741 │   0.815028 │   1.32046 │\n│ C(Region)… │ -0.0626956 │  0.180744 │   0.728685 │  -0.416947 │   0.291556 │  0.939229 │   0.659056 │   1.33851 │\n│ C(Region)… │  0.0412234 │ 0.0412026 │   0.317066 │ -0.0395322 │   0.121979 │   1.04208 │   0.961239 │   1.12973 │\n│ C(Region)… │  0.0135807 │ 0.0404085 │   0.736807 │ -0.0656186 │    0.09278 │   1.01367 │   0.936488 │   1.09722 │\n│ C(Region)… │  0.0525209 │ 0.0505381 │   0.298696 │  -0.046532 │   0.151574 │   1.05392 │   0.954534 │   1.16366 │\n│ C(Region)… │  0.0684027 │ 0.0461369 │    0.13818 │  -0.022024 │   0.158829 │    1.0708 │   0.978217 │   1.17214 │\n│ C(Region)… │  -0.225823 │ 0.0667014 │ 0.0007102… │  -0.356555 │ -0.0950905 │  0.797859 │   0.700084 │  0.909291 │\n│ C(Region)… │   0.302136 │ 0.0895013 │ 0.0007361… │   0.126716 │   0.477555 │   1.35274 │    1.13509 │   1.61213 │\n│ C(Region)… │   0.194511 │ 0.0336491 │ 7.44451e-… │    0.12856 │   0.260462 │   1.21472 │    1.13719 │   1.29753 │\n│ C(Region)… │ -0.0684154 │  0.100887 │   0.497685 │  -0.266151 │    0.12932 │  0.933872 │   0.766323 │   1.13805 │\n│ C(Region)… │   0.045296 │ 0.0545752 │   0.406553 │ -0.0616694 │   0.152261 │   1.04634 │   0.940194 │   1.16446 │\n│ C(Region)… │   0.124617 │ 0.0357804 │ 0.0004961… │   0.054489 │   0.194746 │   1.13271 │      1.056 │     1.215 │\n│ C(Region)… │   0.184642 │     0.115 │   0.108365 │ -0.0407538 │   0.410039 │   1.20279 │   0.960065 │   1.50688 │\n│ C(Area)[B] │  0.0479937 │ 0.0348204 │   0.168104 │ -0.0202531 │   0.116241 │   1.04916 │   0.979951 │   1.12327 │\n│ C(Area)[C] │  0.0629733 │ 0.0450048 │   0.161736 │ -0.0252345 │   0.151181 │     1.065 │   0.975081 │   1.16321 │\n│ C(Area)[D] │   0.141925 │ 0.0682588 │  0.0375968 │ 0.00814051 │    0.27571 │   1.15249 │    1.00817 │   1.31747 │\n│ C(Area)[E] │   0.150928 │ 0.0902039 │  0.0942911 │ -0.0258687 │   0.327724 │   1.16291 │   0.974463 │   1.38781 │\n│ C(Area)[F] │   0.112466 │  0.125283 │   0.369347 │  -0.133084 │   0.358016 │   1.11903 │   0.875392 │   1.43049 │\n│ bs(VehAge, │ -0.0185435 │ 0.0500653 │   0.711094 │   -0.11667 │  0.0795826 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │  0.0581878 │ 0.0404439 │   0.150228 │ -0.0210808 │   0.137456 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │  -0.548899 │  0.194045 │ 0.00467357 │  -0.929221 │  -0.168577 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │   -4.60137 │   1.26765 │ 0.0002835… │   -7.08592 │   -2.11683 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │  0.0953247 │  0.592759 │   0.872239 │   -1.06646 │    1.25711 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │   -1.58949 │ 0.0909744 │          0 │    -1.7678 │   -1.41119 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │  -0.562691 │ 0.0547054 │          0 │  -0.669912 │  -0.455471 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │  -0.273919 │ 0.0873015 │ 0.00170324 │  -0.445027 │  -0.102811 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │   -1.07887 │    0.1152 │          0 │   -1.30466 │  -0.853087 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │   0.497908 │   0.20043 │  0.0129844 │   0.105072 │   0.890745 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │   -60.1755 │   145.392 │   0.678959 │   -345.139 │    224.788 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │   -50.6887 │   143.133 │   0.723237 │   -331.225 │    229.848 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │   -50.0422 │   143.281 │   0.726895 │   -330.868 │    230.784 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │   -50.4448 │   143.254 │   0.724736 │   -331.217 │    230.327 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    -47.502 │   143.286 │   0.740253 │   -328.338 │    233.334 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │   -49.5586 │   143.217 │   0.729314 │   -330.259 │    231.142 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │   -47.4708 │   143.297 │   0.740436 │   -328.327 │    233.386 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ LogDensity │  0.0404592 │ 0.0169434 │  0.0169448 │ 0.00725074 │  0.0736676 │         — │          — │         — │\n└────────────┴────────────┴───────────┴────────────┴────────────┴────────────┴───────────┴────────────┴───────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nGLUM frequency: alpha=0.000120554, l1_ratio=1.0\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                                            GLUM severity relativities                                             </span>\n┏━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> term       </span>┃<span style=\"font-weight: bold\">       coef </span>┃<span style=\"font-weight: bold\"> std_error </span>┃<span style=\"font-weight: bold\">    p_value </span>┃<span style=\"font-weight: bold\">   ci_lower </span>┃<span style=\"font-weight: bold\">   ci_upper </span>┃<span style=\"font-weight: bold\"> relativi… </span>┃<span style=\"font-weight: bold\"> relativit… </span>┃<span style=\"font-weight: bold\"> relativi… </span>┃\n┡━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━┩\n│ intercept  │   -565.999 │   338.875 │  0.0948738 │  -1,230.18 │    98.1834 │         — │          — │         — │\n│ C(VehBran… │ -0.0162899 │  0.104201 │   0.875771 │  -0.220519 │    0.18794 │  0.983842 │   0.802102 │   1.20676 │\n│ C(VehBran… │  0.0722292 │  0.152654 │   0.636101 │  -0.226967 │   0.371425 │    1.0749 │   0.796947 │    1.4498 │\n│ C(VehBran… │  -0.013105 │ 0.0663095 │   0.843331 │  -0.143069 │   0.116859 │   0.98698 │   0.866694 │   1.12396 │\n│ C(VehBran… │   0.155167 │  0.160899 │   0.334859 │   -0.16019 │   0.470524 │   1.16785 │   0.851982 │   1.60083 │\n│ C(VehBran… │  -0.223988 │  0.124187 │  0.0712889 │  -0.467389 │  0.0194143 │  0.799325 │   0.626636 │    1.0196 │\n│ C(VehBran… │ -0.003650… │ 0.0520441 │   0.944081 │  -0.105655 │   0.098354 │  0.996356 │   0.899735 │   1.10335 │\n│ C(VehBran… │   0.027718 │ 0.0737165 │   0.706911 │  -0.116764 │     0.1722 │   1.02811 │   0.889795 │   1.18792 │\n│ C(VehBran… │  0.0144845 │  0.111447 │   0.896592 │  -0.203947 │   0.232916 │   1.01459 │   0.815506 │   1.26228 │\n│ C(VehBran… │ -0.0117378 │ 0.0817031 │   0.885765 │  -0.171873 │   0.148397 │  0.988331 │   0.842086 │   1.15997 │\n│ C(VehBran… │   -0.16739 │ 0.0711841 │  0.0186974 │  -0.306908 │ -0.0278719 │   0.84587 │   0.735718 │  0.972513 │\n│ C(VehPowe… │ -0.0835318 │  0.131925 │    0.52662 │  -0.342101 │   0.175037 │  0.919862 │   0.710277 │   1.19129 │\n│ C(VehPowe… │   0.316842 │  0.211116 │   0.133407 │ -0.0969367 │   0.730621 │   1.37279 │   0.907613 │   2.07637 │\n│ C(VehPowe… │  -0.295709 │  0.130166 │  0.0231003 │   -0.55083 │  -0.040587 │  0.744004 │   0.576471 │  0.960226 │\n│ C(VehPowe… │  -0.494054 │   0.13578 │ 0.0002740… │  -0.760179 │   -0.22793 │  0.610148 │   0.467583 │   0.79618 │\n│ C(VehPowe… │  -0.327769 │  0.165869 │  0.0481471 │  -0.652866 │ -0.0026711 │   0.72053 │   0.520552 │  0.997332 │\n│ C(VehPowe… │ -0.0723736 │  0.100079 │   0.469578 │  -0.268524 │   0.123777 │  0.930183 │   0.764507 │   1.13176 │\n│ C(VehPowe… │  -0.171781 │ 0.0949067 │  0.0702952 │  -0.357795 │  0.0142322 │  0.842163 │   0.699216 │   1.01433 │\n│ C(VehPowe… │ -0.003007… │ 0.0996338 │   0.975917 │  -0.198286 │   0.192271 │  0.996997 │   0.820135 │     1.212 │\n│ C(VehPowe… │ -0.0258705 │  0.096258 │   0.788112 │  -0.214533 │   0.162792 │  0.974461 │   0.806918 │   1.17679 │\n│ C(VehPowe… │  -0.130013 │  0.104959 │   0.215456 │  -0.335729 │   0.075703 │  0.878084 │   0.714817 │   1.07864 │\n│ C(VehPowe… │ -0.0441276 │  0.112572 │   0.695062 │  -0.264764 │   0.176509 │  0.956832 │   0.767387 │   1.19305 │\n│ C(VehGas)… │ -0.0110799 │ 0.0401184 │   0.782409 │ -0.0897105 │  0.0675506 │  0.988981 │   0.914196 │   1.06988 │\n│ C(Region)… │   0.513029 │   0.53096 │    0.33393 │  -0.527634 │    1.55369 │   1.67034 │   0.589999 │   4.72889 │\n│ C(Region)… │  0.0913793 │  0.208585 │    0.66132 │   -0.31744 │   0.500198 │   1.09568 │   0.728011 │   1.64905 │\n│ C(Region)… │  -0.100233 │  0.136403 │   0.462445 │  -0.367578 │   0.167112 │  0.904627 │   0.692409 │   1.18189 │\n│ C(Region)… │  0.0725755 │   0.08262 │   0.379713 │ -0.0893567 │   0.234508 │   1.07527 │   0.914519 │   1.26429 │\n│ C(Region)… │ -0.0107368 │  0.208413 │   0.958914 │  -0.419219 │   0.397745 │  0.989321 │    0.65756 │   1.48846 │\n│ C(Region)… │   0.098515 │  0.176894 │   0.577586 │  -0.248191 │   0.445221 │   1.10353 │   0.780211 │   1.56084 │\n│ C(Region)… │  0.0326214 │  0.102016 │   0.749143 │  -0.167325 │   0.232568 │   1.03316 │   0.845924 │   1.26184 │\n│ C(Region)… │   0.120782 │  0.157476 │   0.443089 │  -0.187865 │   0.429429 │   1.12838 │   0.828727 │   1.53638 │\n│ C(Region)… │   -0.40379 │   0.11098 │ 0.0002743… │  -0.621306 │  -0.186274 │  0.667784 │   0.537242 │  0.830046 │\n│ C(Region)… │ -0.0177073 │  0.312598 │   0.954827 │  -0.630387 │   0.594973 │  0.982449 │   0.532386 │   1.81298 │\n│ C(Region)… │  -0.112097 │  0.086297 │   0.193954 │  -0.281236 │  0.0570418 │  0.893957 │    0.75485 │    1.0587 │\n│ C(Region)… │  0.0785384 │ 0.0953892 │   0.410311 │  -0.108421 │   0.265498 │    1.0817 │    0.89725 │   1.30408 │\n│ C(Region)… │ -0.0647034 │  0.120595 │   0.591589 │  -0.301065 │   0.171658 │  0.937345 │    0.74003 │   1.18727 │\n│ C(Region)… │ -0.0172897 │  0.109505 │   0.874544 │  -0.231915 │   0.197336 │  0.982859 │   0.793014 │   1.21815 │\n│ C(Region)… │  -0.192035 │ 0.0977694 │   0.049511 │   -0.38366 │ -0.000410… │  0.825278 │   0.681363 │  0.999589 │\n│ C(Region)… │  -0.152562 │  0.156493 │   0.329622 │  -0.459283 │    0.15416 │  0.858506 │   0.631736 │   1.16668 │\n│ C(Region)… │   0.020036 │ 0.0772989 │   0.795479 │  -0.131467 │   0.171539 │   1.02024 │   0.876808 │   1.18713 │\n│ C(Region)… │  -0.310849 │  0.119428 │ 0.00924598 │  -0.544922 │  -0.076775 │  0.732825 │   0.579887 │  0.926098 │\n│ C(Region)… │   0.111867 │  0.100628 │   0.266274 │ -0.0853612 │   0.309095 │   1.11836 │   0.918181 │   1.36219 │\n│ C(Region)… │   0.205398 │ 0.0831227 │  0.0134728 │  0.0424804 │   0.368316 │   1.22801 │     1.0434 │    1.4453 │\n│ C(Region)… │  0.0891264 │  0.148689 │   0.548896 │  -0.202298 │   0.380551 │   1.09322 │   0.816851 │   1.46309 │\n│ C(Area)[B] │  -0.156702 │ 0.0967199 │   0.105196 │   -0.34627 │  0.0328651 │  0.854959 │   0.707322 │   1.03341 │\n│ C(Area)[C] │  -0.228887 │  0.122482 │   0.061659 │  -0.468946 │  0.0111732 │  0.795419 │   0.625661 │   1.01124 │\n│ C(Area)[D] │  -0.264779 │  0.178856 │   0.138766 │  -0.615332 │   0.085773 │  0.767375 │   0.540462 │   1.08956 │\n│ C(Area)[E] │  -0.364953 │  0.236129 │   0.122209 │  -0.827758 │  0.0978515 │  0.694229 │   0.437028 │    1.1028 │\n│ C(Area)[F] │  -0.715467 │  0.305036 │  0.0190008 │   -1.31333 │  -0.117607 │  0.488964 │   0.268924 │  0.889045 │\n│ bs(VehAge, │   0.042699 │  0.107686 │   0.691725 │  -0.168361 │   0.253759 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │ -0.0902507 │ 0.0846223 │   0.286192 │  -0.256107 │  0.0756058 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │ -0.0424531 │  0.383231 │   0.911793 │  -0.793572 │   0.708665 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │   -1.14891 │    2.1557 │   0.594057 │     -5.374 │    3.07617 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │  -0.129097 │   1.00528 │   0.897818 │   -2.09941 │    1.84122 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │   -0.85366 │  0.264517 │ 0.00124988 │    -1.3721 │  -0.335217 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │  -0.483991 │  0.172616 │ 0.00504959 │  -0.822312 │  -0.145669 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │  -0.861881 │  0.251029 │ 0.0005960… │   -1.35389 │  -0.369872 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │   0.236194 │  0.328311 │   0.471882 │  -0.407284 │   0.879672 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │    -1.2544 │  0.556914 │  0.0242962 │   -2.34593 │  -0.162869 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    583.126 │   343.912 │  0.0899677 │    -90.929 │   1,257.18 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    573.404 │   338.561 │   0.090332 │    -90.164 │   1,236.97 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    574.082 │   338.934 │  0.0903054 │   -90.2158 │   1,238.38 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    574.116 │   338.844 │   0.090201 │   -90.0055 │   1,238.24 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    574.143 │   338.954 │    0.09029 │   -90.1936 │   1,238.48 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │     574.26 │   338.711 │  0.0899943 │   -89.6013 │   1,238.12 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    574.218 │   338.995 │  0.0902873 │   -90.1996 │   1,238.64 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ LogDensity │  0.0614781 │ 0.0436663 │   0.159159 │ -0.0241063 │   0.147063 │         — │          — │         — │\n└────────────┴────────────┴───────────┴────────────┴────────────┴────────────┴───────────┴────────────┴───────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nGLUM severity: alpha=3.05564, l1_ratio=0.0\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                                          GLUM pure_premium relativities                                           </span>\n┏━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> term       </span>┃<span style=\"font-weight: bold\">       coef </span>┃<span style=\"font-weight: bold\"> std_error </span>┃<span style=\"font-weight: bold\">    p_value </span>┃<span style=\"font-weight: bold\">   ci_lower </span>┃<span style=\"font-weight: bold\">   ci_upper </span>┃<span style=\"font-weight: bold\"> relativi… </span>┃<span style=\"font-weight: bold\"> relativit… </span>┃<span style=\"font-weight: bold\"> relativi… </span>┃\n┡━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━┩\n│ intercept  │   -675.613 │   400.809 │   0.091868 │  -1,461.18 │    109.957 │         — │          — │         — │\n│ C(VehBran… │ 0.00079771 │  0.141034 │   0.995487 │  -0.275624 │    0.27722 │    1.0008 │   0.759098 │   1.31946 │\n│ C(VehBran… │   0.204325 │  0.146876 │   0.164182 │ -0.0835459 │   0.492197 │    1.2267 │   0.919849 │   1.63591 │\n│ C(VehBran… │  -0.248682 │ 0.0804203 │ 0.00198629 │  -0.406303 │ -0.0910608 │  0.779828 │   0.666109 │  0.912962 │\n│ C(VehBran… │   0.174277 │  0.185198 │    0.34669 │  -0.188705 │   0.537259 │   1.19039 │   0.828031 │   1.71131 │\n│ C(VehBran… │  -0.520148 │  0.152282 │ 0.0006361… │  -0.818614 │  -0.221681 │  0.594433 │   0.441042 │  0.801171 │\n│ C(VehBran… │  -0.029306 │  0.062569 │   0.639514 │  -0.151939 │   0.093327 │  0.971119 │   0.859041 │   1.09782 │\n│ C(VehBran… │  0.0631159 │ 0.0815358 │   0.438879 │ -0.0966914 │   0.222923 │   1.06515 │   0.907836 │   1.24972 │\n│ C(VehBran… │   0.100676 │  0.139446 │   0.470308 │  -0.172632 │   0.373985 │   1.10592 │   0.841447 │   1.45351 │\n│ C(VehBran… │  0.0683276 │ 0.0988612 │   0.489473 │  -0.125437 │   0.262092 │   1.07072 │   0.882112 │   1.29965 │\n│ C(VehBran… │  -0.145441 │ 0.0879001 │  0.0980015 │  -0.317722 │  0.0268397 │  0.864641 │   0.727805 │    1.0272 │\n│ C(VehPowe… │  0.0455159 │  0.175414 │   0.795267 │  -0.298288 │    0.38932 │   1.04657 │   0.742087 │   1.47598 │\n│ C(VehPowe… │   0.243294 │  0.205602 │   0.236681 │  -0.159679 │   0.646267 │   1.27544 │   0.852417 │    1.9084 │\n│ C(VehPowe… │  -0.207887 │  0.176167 │   0.237978 │  -0.553168 │   0.137394 │  0.812299 │   0.575125 │   1.14728 │\n│ C(VehPowe… │  -0.499274 │  0.190119 │ 0.00863653 │  -0.871899 │  -0.126648 │  0.606971 │   0.418157 │  0.881044 │\n│ C(VehPowe… │  -0.123846 │  0.237794 │   0.602498 │  -0.589914 │   0.342222 │  0.883516 │   0.554375 │   1.40807 │\n│ C(VehPowe… │  -0.290967 │  0.119512 │  0.0149073 │  -0.525207 │ -0.0567277 │   0.74754 │   0.591433 │  0.944851 │\n│ C(VehPowe… │  -0.327771 │  0.116356 │ 0.00484795 │  -0.555825 │ -0.0997176 │  0.720528 │   0.573599 │  0.905093 │\n│ C(VehPowe… │  -0.135005 │  0.120519 │   0.262629 │  -0.371217 │   0.101207 │  0.873712 │   0.689894 │   1.10651 │\n│ C(VehPowe… │  -0.150072 │  0.116996 │   0.199594 │  -0.379379 │  0.0792361 │  0.860646 │   0.684286 │   1.08246 │\n│ C(VehPowe… │  -0.242459 │  0.129421 │  0.0610108 │  -0.496119 │  0.0112009 │  0.784696 │   0.608889 │   1.01126 │\n│ C(VehPowe… │   -0.04854 │  0.128559 │   0.705751 │  -0.300512 │   0.203432 │  0.952619 │   0.740439 │    1.2256 │\n│ C(VehGas)… │  -0.173942 │  0.048238 │ 0.0003110… │  -0.268486 │ -0.0793968 │  0.840346 │   0.764536 │  0.923673 │\n│ C(Region)… │   0.774417 │  0.656709 │   0.238303 │  -0.512709 │    2.06154 │   2.16933 │   0.598871 │   7.85808 │\n│ C(Region)… │   0.252901 │  0.214707 │    0.23884 │  -0.167917 │   0.673719 │   1.28776 │   0.845424 │   1.96152 │\n│ C(Region)… │  -0.143262 │   0.16577 │   0.387469 │  -0.468166 │   0.181643 │  0.866527 │    0.62615 │   1.19919 │\n│ C(Region)… │  0.0716416 │ 0.0933131 │   0.442633 │  -0.111249 │   0.254532 │   1.07427 │   0.894716 │   1.28986 │\n│ C(Region)… │  0.0317919 │  0.247132 │    0.89764 │  -0.452579 │   0.516163 │    1.0323 │   0.635986 │   1.67559 │\n│ C(Region)… │  0.0170777 │  0.170403 │    0.92017 │  -0.316906 │   0.351061 │   1.01722 │     0.7284 │   1.42057 │\n│ C(Region)… │  0.0898569 │   0.11376 │   0.429597 │  -0.133109 │   0.312822 │   1.09402 │    0.87537 │   1.36728 │\n│ C(Region)… │  0.0201442 │  0.195477 │   0.917922 │  -0.362984 │   0.403272 │   1.02035 │   0.695598 │   1.49671 │\n│ C(Region)… │  -0.343906 │  0.186109 │  0.0646211 │  -0.708674 │  0.0208617 │  0.708996 │   0.492297 │   1.02108 │\n│ C(Region)… │ -0.0372713 │  0.361641 │   0.917914 │  -0.746074 │   0.671531 │  0.963415 │   0.474225 │   1.95723 │\n│ C(Region)… │  -0.113737 │  0.102443 │   0.266892 │   -0.31452 │  0.0870471 │  0.892493 │   0.730139 │   1.09095 │\n│ C(Region)… │  0.0628482 │  0.109533 │   0.566113 │  -0.151832 │   0.277528 │   1.06487 │   0.859133 │   1.31986 │\n│ C(Region)… │ 0.00683957 │   0.15174 │   0.964048 │  -0.290565 │   0.304244 │   1.00686 │   0.747841 │    1.3556 │\n│ C(Region)… │  0.0389633 │  0.127259 │   0.759472 │  -0.210459 │   0.288386 │   1.03973 │   0.810212 │   1.33427 │\n│ C(Region)… │  -0.390191 │  0.124187 │ 0.00167819 │  -0.633593 │  -0.146789 │  0.676928 │   0.530682 │  0.863476 │\n│ C(Region)… │   0.144894 │   0.19828 │    0.46493 │  -0.243729 │   0.533516 │   1.15592 │     0.7837 │   1.70492 │\n│ C(Region)… │   0.178409 │ 0.0870759 │  0.0404727 │ 0.00774343 │   0.349075 │   1.19531 │    1.00777 │   1.41776 │\n│ C(Region)… │  -0.367336 │   0.16143 │  0.0228754 │  -0.683733 │ -0.0509385 │  0.692577 │   0.504729 │  0.950337 │\n│ C(Region)… │   0.206376 │  0.117741 │  0.0796371 │ -0.0243922 │   0.437145 │   1.22922 │   0.975903 │   1.54828 │\n│ C(Region)… │   0.342197 │ 0.0949832 │ 0.0003149… │   0.156034 │   0.528361 │   1.40804 │    1.16887 │   1.69615 │\n│ C(Region)… │   0.268575 │  0.188656 │   0.154556 │  -0.101184 │   0.638334 │    1.3081 │   0.903767 │   1.89332 │\n│ C(Area)[B] │  -0.163041 │  0.116219 │   0.160653 │  -0.390825 │  0.0647438 │  0.849557 │   0.676498 │   1.06689 │\n│ C(Area)[C] │  -0.208896 │  0.146687 │   0.154419 │  -0.496396 │  0.0786047 │   0.81148 │    0.60872 │   1.08178 │\n│ C(Area)[D] │  -0.200112 │  0.214857 │   0.351661 │  -0.621224 │      0.221 │  0.818639 │   0.537286 │   1.24732 │\n│ C(Area)[E] │  -0.294687 │  0.283862 │   0.299206 │  -0.851046 │   0.261671 │  0.744764 │   0.426968 │    1.2991 │\n│ C(Area)[F] │  -0.770636 │   0.36571 │  0.0350974 │   -1.48741 │ -0.0538576 │  0.462719 │   0.225956 │  0.947567 │\n│ bs(VehAge, │  0.0631747 │  0.120471 │   0.600002 │  -0.172944 │   0.299294 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │ -0.0260766 │ 0.0989962 │   0.792234 │  -0.220106 │   0.167952 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │  -0.420064 │  0.433614 │   0.332669 │   -1.26993 │   0.429803 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │   -7.23863 │   2.16709 │ 0.0008369… │    -11.486 │   -2.99122 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(VehAge, │   0.423302 │   1.02474 │   0.679545 │   -1.58514 │    2.43175 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │    -2.4031 │  0.295043 │ 4.44089e-… │   -2.98137 │   -1.82482 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │  -0.939802 │  0.181693 │ 2.31025e-… │   -1.29591 │   -0.58369 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │   -1.00683 │  0.282008 │ 0.0003566… │   -1.55956 │  -0.454104 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │  -0.866851 │  0.388036 │  0.0254868 │   -1.62739 │  -0.106314 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(DrivAg… │  -0.268537 │  0.666206 │   0.686886 │   -1.57428 │     1.0372 │         — │          — │         — │\n│ df=5,      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    683.899 │   406.876 │  0.0927914 │   -113.563 │   1,481.36 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    680.517 │   400.414 │  0.0892183 │   -104.279 │   1,465.31 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    682.092 │    400.87 │  0.0888435 │   -103.598 │   1,467.78 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    681.758 │   400.759 │  0.0889118 │   -103.716 │   1,467.23 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │      684.7 │   400.902 │   0.087655 │   -101.053 │   1,470.45 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │    682.996 │   400.577 │  0.0881893 │   -102.122 │   1,468.11 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ bs(BonusM… │     685.07 │   401.002 │   0.087563 │    -100.88 │   1,471.02 │         — │          — │         — │\n│ knots=[55, │            │           │            │            │            │           │            │           │\n│ 65, 80,    │            │           │            │            │            │           │            │           │\n│ 100],      │            │           │            │            │            │           │            │           │\n│ lower_bou… │            │           │            │            │            │           │            │           │\n│ upper_bou… │            │           │            │            │            │           │            │           │\n│ LogDensity │   0.120147 │ 0.0520889 │  0.0210785 │  0.0180546 │   0.222239 │         — │          — │         — │\n└────────────┴────────────┴───────────┴────────────┴────────────┴────────────┴───────────┴────────────┴───────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nGLUM pure_premium: alpha=0.403495, l1_ratio=0.5\n```\n:::\n:::\n\n\n## Compare fitted conditional distributions on training policies {#sec-conditional-diagnostics}\n\nThe uncapped exploration used shared portfolio means. Here the\n[GLUM models](#sec-glum-benchmark) supply means that vary with policy\ncharacteristics. A conditional\ndistribution describes variation in outcomes at a given policy's predicted\nmean, exposure, and claim count where applicable. The table lists the working\nreferences for each component, using the capped modelling targets.\n\nThe survival curves compare upper tails, the zero-mass table compares the\nprobabilities of no claims and no loss, and the Pearson residual check\ncompares squared errors scaled by the assumed variance. Empirical and\nreference curves use matching weights: exposure for counts and policy totals,\nclaim count for severity. Their sum is called risk volume. Agreement in these\npooled training views cannot establish correctness for each policy or\nperformance on the test set.\n\nHere $e_i$ is policy exposure, $n_i$ is claim count, $\\hat\\lambda_i$ is\npredicted annual frequency, and $\\hat\\mu_i$ is predicted severity or pure\npremium, according to the row. Base dispersion $\\phi$ controls variance\nbefore adjustment for claim count or exposure; $p$ is the selected Tweedie\nvariance power.\n\n| Observable | Conditional reference | Curve weight |\n| --- | --- | --- |\n| Policy claim count | Poisson mean $e_i\\hat\\lambda_i$ | Exposure $e_i$ |\n| Positive capped policy-average severity | Gamma shape $n_i/\\phi$, scale $\\phi\\hat\\mu_i/n_i$ | Claim count $n_i$ |\n| Capped policy total | Tweedie mean $e_i\\hat\\mu_i$, dispersion $\\phi e_i^{1-p}$ | Exposure $e_i$ |\n\n### Fit dispersion parameters; means stay fixed\n\nKeep the GLUM predicted rates fixed. Estimate Gamma base dispersion for\nseverity, Tweedie base dispersion for pure premium, and Negative Binomial\nshape for frequency on every eligible training row. The Poisson reference\nneeds only the predicted policy count, so it has no additional parameter to fit.\n\nThe Negative Binomial (NB2) form used here has variance $m_i+m_i^2/r$,\nwhere $m_i=e_i\\hat\\lambda_i$ is the predicted policy count and $r$ is\nthe shape parameter. Smaller $r$ allows more variation; as $r$ grows, the\nreference approaches Poisson, whose variance is $m_i$.\nThis NB overlay is a dispersion diagnostic; the fitted frequency pricing\nmodel remains Poisson.\n\nAfter those fits finish, sample up to 20,000 policies per component with\nseed 42 and reuse each component's rows, predictions, and weights throughout.\n\n::: {#fit-diagnostic-parameters .cell execution_count=17}\n``` {.python .cell-code}\ntraining_rows = {}\ntraining_predictions = {}\nfor component in TARGET_SPECS:\n    rows, _, _ = target_and_weight(splits.train, component)\n    training_rows[component] = rows\n    training_predictions[component] = pd.Series(\n        glum_models[component].predict(rows), index=rows.index, dtype=float\n    )\n\nseverity_train = training_rows[\"severity\"]\ngamma_dispersion = fit_gamma_dispersion(\n    severity_train[\"Severity\"],\n    training_predictions[\"severity\"],\n    severity_train[\"ClaimNb\"],\n)\nnb_shape = fit_negative_binomial_shape(\n    training_rows[\"frequency\"][\"ClaimNb\"],\n    training_rows[\"frequency\"][\"Exposure\"] * training_predictions[\"frequency\"],\n)\ntweedie_dispersion = fit_tweedie_dispersion(\n    training_rows[\"pure_premium\"][\"PurePremium\"],\n    training_predictions[\"pure_premium\"],\n    training_rows[\"pure_premium\"][\"Exposure\"],\n    selected_power,\n)\ndispersions = {\"frequency\": 1.0, \"severity\": gamma_dispersion, \"pure_premium\": tweedie_dispersion}\n```\n:::\n\n\n::: {#cell-sample-diagnostic-policies .cell execution_count=18}\n``` {.python .cell-code}\ndiagnostic_rows = {}\ndiagnostic_predictions = {}\nfor component, rows in training_rows.items():\n    sample = rows.sample(n=min(20_000, len(rows)), random_state=42)\n    diagnostic_rows[component] = sample\n    diagnostic_predictions[component] = training_predictions[component].loc[sample.index]\nprint_frame(\n    \"Training diagnostic scope\",\n    pd.DataFrame({\n        \"eligible_training_policies\": {name: len(rows) for name, rows in training_rows.items()},\n        \"plotted_policies\": {name: len(rows) for name, rows in diagnostic_rows.items()},\n        \"base_dispersion\": dispersions,\n    }),\n)\nprint(f\"NB shape: {nb_shape:.6g} (infinity denotes the Poisson limit)\")\n```\n\n::: {#sample-diagnostic-policies .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                            Training diagnostic scope                             </span>\n┏━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> index        </span>┃<span style=\"font-weight: bold\"> eligible_training_policies </span>┃<span style=\"font-weight: bold\"> plotted_policies </span>┃<span style=\"font-weight: bold\"> base_dispersion </span>┃\n┡━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩\n│ frequency    │                     542410 │            20000 │               1 │\n│ severity     │                      19955 │            19955 │         1.17155 │\n│ pure_premium │                     542410 │            20000 │         313.757 │\n└──────────────┴────────────────────────────┴──────────────────┴─────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\nNB shape: 1.17491 (infinity denotes the Poisson limit)\n```\n:::\n:::\n\n\n### Fitted zero mass\n\nFrequency and pure premium can equal zero. The observed column gives the\nshare of exposure on claim-free or zero-loss policies; the fitted column\naverages their predicted zero probabilities with the same exposure weights.\nThese are exposure shares, rather than fractions of policy records.\n\n::: {#cell-diagnostic-zero-mass .cell execution_count=19}\n``` {.python .cell-code}\nfrequency_rows = diagnostic_rows[\"frequency\"]\nfrequency_weight = frequency_rows[\"Exposure\"].to_numpy(dtype=float)\nfrequency_mean = (\n    frequency_weight * diagnostic_predictions[\"frequency\"].to_numpy(dtype=float)\n)\npure_premium_rows = diagnostic_rows[\"pure_premium\"]\npure_premium_weight = pure_premium_rows[\"Exposure\"].to_numpy(dtype=float)\npure_premium_mean = (\n    pure_premium_weight\n    * diagnostic_predictions[\"pure_premium\"].to_numpy(dtype=float)\n)\ntweedie_intensity = pure_premium_mean ** (2 - selected_power) / (\n    (2 - selected_power)\n    * tweedie_dispersion\n    * pure_premium_weight ** (1 - selected_power)\n)\nprint_frame(\n    \"Risk-volume-weighted zero mass\",\n    pd.DataFrame(\n        {\n            \"observed\": [\n                np.average(frequency_rows[\"ClaimNb\"].eq(0), weights=frequency_weight),\n                np.average(\n                    pure_premium_rows[\"ClaimAmountCapped\"].eq(0),\n                    weights=pure_premium_weight,\n                ),\n            ],\n            \"fitted\": [\n                np.average(poisson.pmf(0, frequency_mean), weights=frequency_weight),\n                np.average(np.exp(-tweedie_intensity), weights=pure_premium_weight),\n            ],\n        },\n        index=pd.Index([\"Policy claim count\", \"Capped policy total\"], name=\"observable\"),\n    ),\n)\n```\n\n::: {#diagnostic-zero-mass .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">       Risk-volume-weighted zero mass        </span>\n┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> observable          </span>┃<span style=\"font-weight: bold\"> observed </span>┃<span style=\"font-weight: bold\">   fitted </span>┃\n┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━┩\n│ Policy claim count  │ 0.950113 │  0.94679 │\n│ Capped policy total │ 0.950113 │ 0.947155 │\n└─────────────────────┴──────────┴──────────┘\n</pre>\n```\n:::\n:::\n\n\n### Policy claim-count tail\n\nAt each count threshold, the curves show the probability of exceeding that\ncount, averaged with exposure weights. The Poisson and Negative Binomial\nreferences keep the same fitted policy means.\n\n::: {#frequency-sf .cell execution_count=20}\n``` {.python .cell-code}\npoisson_ccdf_diagnostic(diagnostic_rows[\"frequency\"], diagnostic_predictions[\"frequency\"], nb_shape)\n```\n\n::: {#frequency-sf-1 .cell-output .cell-output-display execution_count=20}\n```\n(<Figure size 624x432 with 1 Axes>,\n <Axes: title={'center': 'Frequency (n=20,000 policies)'}, xlabel='ClaimNb', ylabel='SF: P(Y > x)'>)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/frequency-sf-output-2.png){#frequency-sf-2 width=613 height=422}\n:::\n:::\n\n\nThe fitted NB shape $r=1.17$ broadens the count tail, but it does not uniformly\nmatch the pooled empirical survival better: the observed two-or-more mass lies\nbetween the two references, while both references overstate the farther tail.\n\n### Positive capped policy-average severity tail\n\nThe curves show the probability that capped policy-average severity exceeds\neach amount, using claim-count weights. The Gamma reference accounts for\nclaim count through its policy-specific shape and scale.\nThe 128 logarithmic thresholds run from the smallest positive sampled\nseverity to its maximum; probabilities retain the full claim-count denominator.\n\n::: {#severity-sf .cell execution_count=21}\n``` {.python .cell-code}\ngamma_ccdf_diagnostic(diagnostic_rows[\"severity\"], diagnostic_predictions[\"severity\"], gamma_dispersion)\n```\n\n::: {#severity-sf-1 .cell-output .cell-output-display execution_count=21}\n```\n(<Figure size 624x432 with 1 Axes>,\n <Axes: title={'center': 'Severity (n=19,955 policies)'}, xlabel='Capped policy-average severity (EUR)', ylabel='SF: P(Y > x)'>)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/severity-sf-output-2.png){#severity-sf-2 width=613 height=420}\n:::\n:::\n\n\nThe Gamma reference misses the observed shoulder around EUR 1,000, overstates\npart of the middle tail, and then decays too quickly to reproduce the upper tail.\n\n### Capped policy-total tail\n\nThe curves show the probability that a capped policy total exceeds each\namount, using exposure weights. The Tweedie reference converts fitted\npure-premium rates to policy totals and uses exposure-adjusted dispersion.\nThe 128 logarithmic thresholds cover the full positive sampled range, with\nall sampled exposure retained in the probability denominator, including zero-loss policies.\n\n::: {#pure-premium-sf .cell execution_count=22}\n``` {.python .cell-code}\ntweedie_ccdf_diagnostic(diagnostic_rows[\"pure_premium\"], diagnostic_predictions[\"pure_premium\"], selected_power, tweedie_dispersion)\n```\n\n::: {#pure-premium-sf-1 .cell-output .cell-output-display execution_count=22}\n```\n(<Figure size 624x432 with 1 Axes>,\n <Axes: title={'center': 'Pure Premium (n=20,000 policies)'}, xlabel='Capped policy total (EUR)', ylabel='SF: P(Y > x)'>)\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/pure-premium-sf-output-2.png){#pure-premium-sf-2 width=613 height=420}\n:::\n:::\n\n\nThe Tweedie survival falls much faster than the empirical curve,\nunderstating the larger capped policy totals.\n\n### Conditional residual dispersion by area\n\nTo compare variation across areas, average squared residuals after scaling\nthem for each policy's weight and predicted mean. Use all eligible training\nrows and keep the means fixed. For area $g$,\n\n$$\nD_g=\\frac{1}{n_g}\\sum_{i\\in g}\nw_i\\frac{(y_i-\\hat\\mu_i)^2}{\\hat\\mu_i^p}.\n$$\n\nHere $n_g$ counts eligible policies in area $g$, $y_i$ is the observed\ntarget, and $\\hat\\mu_i$ is its predicted mean. The weight $w_i$ is exposure\nfor frequency and pure premium, or claim count for severity. The table's\n`risk_volume` is $\\sum_{i\\in g}w_i$; $D_g$ divides by policy count $n_g$.\n\nFix $p=1$ for frequency, $p=2$ for severity, and the selected power for pure\npremium. Under the working variance assumption, variance is\n$\\phi\\hat\\mu_i^p/w_i$. Compare $D_g$ with 1 for Poisson or the fitted\nbase dispersion $\\hat\\phi$ for Gamma and Tweedie. Read it alongside the\nweighted observed and predicted means, since a mean error also increases\nsquared residuals.\n\n::: {#conditional-dispersion .cell execution_count=23}\n``` {.python .cell-code}\nfor component, rows in training_rows.items():\n    print_frame(\n        f\"Training {component} residual dispersion by area\",\n        conditional_dispersion_table(rows, training_predictions[component], \"Area\", component, selected_power),\n    )\nconditional_dispersion_diagnostic(splits.train, training_predictions, \"Area\", selected_power, dispersions)\n```\n\n::: {#conditional-dispersion-1 .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">               Training frequency residual dispersion by area                </span>\n┏━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> Area </span>┃<span style=\"font-weight: bold\">      n </span>┃<span style=\"font-weight: bold\"> risk_volume </span>┃<span style=\"font-weight: bold\"> observed_rate </span>┃<span style=\"font-weight: bold\"> predicted_rate </span>┃<span style=\"font-weight: bold\"> dispersion </span>┃\n┡━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩\n│ A    │  83279 │    49,705.4 │     0.0544206 │      0.0554356 │    1.77747 │\n│ B    │  60438 │    34,550.3 │      0.061736 │      0.0614093 │    2.07591 │\n│ C    │ 153433 │    83,445.3 │     0.0681165 │      0.0679283 │    1.66244 │\n│ D    │ 121192 │    61,641.9 │     0.0838716 │      0.0836408 │    2.51618 │\n│ E    │ 109580 │    51,014.4 │     0.0952084 │      0.0949481 │    1.61347 │\n│ F    │  14488 │    6,541.22 │     0.0912674 │      0.0920508 │    1.76841 │\n└──────┴────────┴─────────────┴───────────────┴────────────────┴────────────┘\n</pre>\n```\n:::\n\n::: {#conditional-dispersion-2 .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">               Training severity residual dispersion by area               </span>\n┏━━━━━━┳━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> Area </span>┃<span style=\"font-weight: bold\">    n </span>┃<span style=\"font-weight: bold\"> risk_volume </span>┃<span style=\"font-weight: bold\"> observed_rate </span>┃<span style=\"font-weight: bold\"> predicted_rate </span>┃<span style=\"font-weight: bold\"> dispersion </span>┃\n┡━━━━━━╇━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩\n│ A    │ 2603 │       2,705 │       1,984.3 │       1,865.08 │    13.1926 │\n│ B    │ 2045 │       2,133 │      1,811.45 │       1,836.81 │    6.38591 │\n│ C    │ 5403 │       5,684 │      1,814.42 │       1,837.69 │    8.31129 │\n│ D    │ 4830 │       5,170 │      1,914.94 │       1,872.38 │     8.7384 │\n│ E    │ 4522 │       4,857 │      1,892.41 │       1,868.18 │    7.36899 │\n│ F    │  552 │         597 │      1,392.14 │       1,731.61 │    5.76591 │\n└──────┴──────┴─────────────┴───────────────┴────────────────┴────────────┘\n</pre>\n```\n:::\n\n::: {#conditional-dispersion-3 .cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">              Training pure_premium residual dispersion by area              </span>\n┏━━━━━━┳━━━━━━━━┳━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> Area </span>┃<span style=\"font-weight: bold\">      n </span>┃<span style=\"font-weight: bold\"> risk_volume </span>┃<span style=\"font-weight: bold\"> observed_rate </span>┃<span style=\"font-weight: bold\"> predicted_rate </span>┃<span style=\"font-weight: bold\"> dispersion </span>┃\n┡━━━━━━╇━━━━━━━━╇━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━┩\n│ A    │  83279 │    49,705.4 │       107.987 │        104.448 │   5,956.96 │\n│ B    │  60438 │    34,550.3 │       111.832 │        111.114 │   2,835.99 │\n│ C    │ 153433 │    83,445.3 │       123.592 │        124.416 │   4,538.69 │\n│ D    │ 121192 │    61,641.9 │       160.609 │        154.444 │   4,831.55 │\n│ E    │ 109580 │    51,014.4 │       180.173 │         176.16 │    5,176.3 │\n│ F    │  14488 │    6,541.22 │       127.057 │        144.393 │    986.043 │\n└──────┴────────┴─────────────┴───────────────┴────────────────┴────────────┘\n</pre>\n```\n:::\n\n::: {#conditional-dispersion-4 .cell-output .cell-output-display execution_count=23}\n```\n(<Figure size 1440x432 with 3 Axes>,\n array([<Axes: title={'center': 'Frequency (n=542,410)'}, xlabel='Area', ylabel='Mean scaled residual square'>,\n        <Axes: title={'center': 'Severity (n=19,955)'}, xlabel='Area', ylabel='Mean scaled residual square'>,\n        <Axes: title={'center': 'Pure Premium (n=542,410)'}, xlabel='Area', ylabel='Mean scaled residual square'>],\n       dtype=object))\n```\n:::\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/conditional-dispersion-output-5.png){#conditional-dispersion-5 width=1430 height=422}\n:::\n:::\n\n\nArea frequency means are close to their fitted values, yet Pearson dispersion\nis 1.61–2.52 in every area against the Poisson reference of 1. That gap does\nnot by itself identify a count family. A single claim on a short exposure\ninflates the squared Pearson residual, and an NB2 reference at the fitted\nshape $r=1.17$ would raise each policy's expected scaled squared residual\nfrom 1 to $1+m_i/r$, an increase of only a few percent at typical policy\nmeans. This is much smaller than the area dispersions of 1.61–2.52. The count survival panel\nagrees that $r=1.17$ is a mild overlay, since the observed two-or-more mass\nlies between the Poisson and NB references and both overstate the farther\ntail. Poisson therefore remains a working mean and deviance model; these\ndiagnostics neither validate its full count distribution nor support a\nspecific alternative.\n\nSeverity dispersion is 5.77–13.19 against the fitted Gamma reference of 1.17;\npure-premium dispersion is 986–5,957 against the fitted Tweedie reference of\n314. Most area means remain close, although Area F has a visible mean gap.\nWe therefore use Gamma and Tweedie as working\ndistributions for mean fitting, without claiming they describe the full\nvariation in outcomes.\n\n::: {.callout-note collapse=\"true\"}\n## Look inside: conditional diagnostics\n\n`weighted_empirical_ccdf` validates values and weights, aggregates equal\noutcomes, and evaluates survival with the full denominator.\n\n::: {#d8a4d3b4 .cell execution_count=24}\n``` {.python .cell-code}\nshow_source(weighted_empirical_ccdf)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef weighted_empirical_ccdf(\n    values: np.ndarray, weights: np.ndarray\n) -> tuple[np.ndarray, np.ndarray]:\n    \"\"\"Return sorted ``values`` and their weighted empirical CCDF (1 − F̂).\"\"\"\n    sorted_x, cdf = weighted_empirical_cdf(values, weights)\n    return sorted_x, 1.0 - cdf\n\n```\n:::\n:::\n\n\n`fit_negative_binomial_shape` uses a log-beta likelihood, optimizes log shape\nover $[10^{-8},10^8]$, and compares the result with the exact Poisson limit.\nAn improvement of at most `1e-8` per policy returns infinity; optimizer failure,\ninvalid estimates, or a material boundary optimum raise instead of falling\nback to moments.\n\nThe sampled rows retain indexed predictions in their sampled order. Reference\ncurves evaluate 128 thresholds in batches of at most 8 thresholds by 512\npolicies. Tweedie Poisson-Gamma terms accumulate sequentially with a relative\nomitted-mass bound of `1e-10` and a `10_000`-term limit.\n\n`conditional_dispersion_table` computes scaled residual squares at the fixed\ncomponent power, divides them by policy count within area, and reports weighted\nobserved and predicted means using group risk volume.\n\n::: {#65d77661 .cell execution_count=25}\n``` {.python .cell-code}\nshow_source(conditional_dispersion_table)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef conditional_dispersion_table(\n    data: pd.DataFrame, mean: pd.Series, by: str, response: str, tweedie_power: float\n) -> pd.DataFrame:\n    \"\"\"Report fixed-power residual dispersion, dividing by row count, not risk volume.\"\"\"\n    target, prediction, weight = _diagnostic_inputs(data, mean, response)\n    power = {\"frequency\": 1.0, \"severity\": 2.0, \"pure_premium\": tweedie_power}[response]\n    if response == \"pure_premium\" and not 1 < power < 2:\n        raise ValueError(\"tweedie_power must lie in (1, 2)\")\n    frame = pd.DataFrame(\n        {\n            by: data[by],\n            \"risk_volume\": weight,\n            \"observed_rate\": weight * target,\n            \"predicted_rate\": weight * prediction,\n            \"dispersion\": weight * (target - prediction) ** 2 / prediction**power,\n        }\n    )\n    grouped = frame.groupby(by, observed=True, sort=True, dropna=False)\n    table = grouped.sum()\n    table.insert(0, \"n\", grouped.size())\n    table[[\"observed_rate\", \"predicted_rate\"]] = table[\n        [\"observed_rate\", \"predicted_rate\"]\n    ].div(table[\"risk_volume\"], axis=0)\n    table[\"dispersion\"] /= table[\"n\"]\n    return table.reset_index()\n\n```\n:::\n:::\n\n\n`tweedie_ccdf_diagnostic` passes the supplied sample, predictions, power, and\nbase dispersion to the shared survival plotter; it neither fits parameters nor\nsamples rows.\n\n::: {#70a4a7a7 .cell execution_count=26}\n``` {.python .cell-code}\nshow_source(tweedie_ccdf_diagnostic)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef tweedie_ccdf_diagnostic(\n    data: pd.DataFrame,\n    mean: pd.Series,\n    tweedie_power: float,\n    dispersion: float,\n    axes=None,\n):\n    \"\"\"Survival for the same capped policy totals and fitted Tweedie reference as the CDF.\"\"\"\n    return _conditional_diagnostic(\n        data, mean, \"pure_premium\", dispersion, tweedie_power, axes, survival=True\n    )\n\n```\n:::\n:::\n\n\n:::\n\n## Fit a nonlinear LightGBM challenger\n\nTune a small LightGBM grid with early stopping on development\nvalidation, then refit each selected model on the final training data.\n\nUse the same train/test protocol for every model and document the search\nspace. Before accepting extra complexity, define the required deviance gain\nand checks of relativities and stability across resamples or future periods.\nThis tutorial does not set acceptance thresholds or perform those stability\nchecks.\n\nThe `fit_lightgbm` helper grid-searches\n$\\mathrm{num\\_leaves} \\in \\{15, 31\\}$ and\n$\\mathrm{min\\_child\\_samples} \\in \\{100, 500\\}$ (smaller $\\{20, 50\\}$ for\nseverity to keep leaves from collapsing on the smaller claim-bearing set)\nwith early stopping on development-validation deviance, then refits the\nchosen configuration on all training rows using `best_iteration`. The full\ngrid, the Tweedie objective, and the early-stopping recipe are in\n[`src/nonlife_pureprem/pure_premium.py`](https://github.com/ThomasBury/nonlife-pureprem/blob/main/src/nonlife_pureprem/pure_premium.py)\n(`fit_lightgbm`).\n\n::: {#4ac9d504 .cell execution_count=27}\n``` {.python .cell-code}\nlightgbm_models = {}\nfor component in TARGET_SPECS:\n    model, tuning = fit_lightgbm(\n        splits.development_train,\n        splits.development_validation,\n        splits.train,\n        component,\n        selected_power,\n        max_rounds=max_rounds,\n        early_stopping_rounds=early_stopping_rounds,\n    )\n    lightgbm_models[component] = model\n    print_frame(f\"LightGBM {component} tuning\", tuning)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                        LightGBM frequency tuning                        </span>\n┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> num_leaves </span>┃<span style=\"font-weight: bold\"> min_child_samples </span>┃<span style=\"font-weight: bold\"> best_iteration </span>┃<span style=\"font-weight: bold\"> validation_deviance </span>┃\n┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩\n│         31 │               100 │            283 │            0.450449 │\n│         15 │               100 │            494 │            0.450713 │\n│         31 │               500 │            336 │            0.451091 │\n│         15 │               500 │            496 │            0.451604 │\n└────────────┴───────────────────┴────────────────┴─────────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                        LightGBM severity tuning                         </span>\n┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> num_leaves </span>┃<span style=\"font-weight: bold\"> min_child_samples </span>┃<span style=\"font-weight: bold\"> best_iteration </span>┃<span style=\"font-weight: bold\"> validation_deviance </span>┃\n┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩\n│         15 │                50 │             12 │             1.21968 │\n│         15 │                20 │              9 │             1.22123 │\n│         31 │                20 │              7 │             1.22221 │\n│         31 │                50 │              7 │             1.22225 │\n└────────────┴───────────────────┴────────────────┴─────────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                      LightGBM pure_premium tuning                       </span>\n┏━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> num_leaves </span>┃<span style=\"font-weight: bold\"> min_child_samples </span>┃<span style=\"font-weight: bold\"> best_iteration </span>┃<span style=\"font-weight: bold\"> validation_deviance </span>┃\n┡━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━┩\n│         31 │               100 │             53 │             72.3425 │\n│         15 │               100 │             74 │             72.4426 │\n│         15 │               500 │             63 │              72.444 │\n│         31 │               500 │             46 │             72.4643 │\n└────────────┴───────────────────┴────────────────┴─────────────────────┘\n</pre>\n```\n:::\n:::\n\n\n## Final locked test audit: produce four pure-premium estimates {#sec-test-audit}\n\nEach approach estimates expected claim cost per unit exposure for the same\ntest policies. GLUM and LightGBM each produce two estimates: predicted\nfrequency multiplied by predicted severity, and a direct Tweedie prediction.\n\nPair frequency and severity from the same model family; a hybrid pairing\nwould need its own validation. Keep predictions positive and evaluate all\nfour alternatives on the identical test set.\n\n::: {#9a05ef7e .cell execution_count=28}\n``` {.python .cell-code}\ntest_features = lightgbm_frame(splits.test)\nglum_frequency = np.asarray(\n    glum_models[\"frequency\"].predict(splits.test), dtype=float\n)\nglum_severity = np.asarray(\n    glum_models[\"severity\"].predict(splits.test), dtype=float\n)\nlgb_frequency = np.asarray(\n    lightgbm_models[\"frequency\"].predict(test_features), dtype=float\n)\nlgb_severity = np.asarray(\n    lightgbm_models[\"severity\"].predict(test_features), dtype=float\n)\nfrequency_predictions = {\"GLUM\": glum_frequency, \"LightGBM\": lgb_frequency}\n\nseverity_rows, _, _ = target_and_weight(splits.test, \"severity\")\nseverity_predictions = {\n    \"GLUM\": np.asarray(glum_models[\"severity\"].predict(severity_rows), dtype=float),\n    \"LightGBM\": np.asarray(\n        lightgbm_models[\"severity\"].predict(lightgbm_frame(severity_rows)),\n        dtype=float,\n    ),\n}\npure_premium_predictions = {\n    \"GLUM frequency x severity\": glum_frequency * glum_severity,\n    \"LightGBM frequency x severity\": lgb_frequency * lgb_severity,\n    \"GLUM Tweedie\": np.asarray(\n        glum_models[\"pure_premium\"].predict(splits.test), dtype=float\n    ),\n    \"LightGBM Tweedie\": np.asarray(\n        lightgbm_models[\"pure_premium\"].predict(test_features), dtype=float\n    ),\n}\ny_test = splits.test[\"PurePremium\"].to_numpy(dtype=float)\nexposure = splits.test[\"Exposure\"].to_numpy(dtype=float)\n```\n:::\n\n\nThe `y_test` and `exposure` arrays defined above are the observed pure\npremium and the exposure of every held-out test policy. All performance\ntables and plots below belong to this final audit, with eligible claim-bearing\ntest rows used for severity. Model and parameter choices are now locked.\nAny recalibration or model revision informed by these results requires a new\nevaluation cycle with data that did not inform that revision.\n\n## Compare predictive accuracy with the proper score\n\nWeighted mean deviance measures prediction error using Poisson deviance for\nfrequency, Gamma for severity, and Tweedie for pure premium. Exposure weights\napply to frequency and pure premium; claim-count weights apply to severity.\nA proper score rewards the correct conditional mean in expectation, even\nwhen the working distribution does not describe the full outcome distribution.\n\nThe output contains five measures. Read each within the same response and\nweighting convention; compare deviance and D2 at the same family and power.\n\n| Column | What it measures | How to read it | Limit |\n| --- | --- | --- | --- |\n| `weighted_deviance` | Prediction error under the chosen deviance | Lower is better | A unit is not a euro; frequency and severity scores have different scales. |\n| `D2` | $1-\\mathrm{deviance}/\\mathrm{null\\_deviance}$ | Higher is better; zero matches the constant-mean baseline | The baseline predicts the evaluation rows' weighted mean for every row. |\n| `actual_expected` (A/E) | Weighted observed total divided by predicted total | Near 1 means the totals agree; above 1 means the model predicts too little in total | Errors can cancel between segments. |\n| `raw_gini` | Ranking of observed losses by predicted rate | Higher positive values indicate better ranking | Rescaling predictions can change totals without changing ranks. |\n| `normalized_gini` | Raw Gini divided by Gini from ordering on observed outcomes | 1 matches that observed-outcome ordering | Uses the same outcomes and weights as its denominator; it does not measure calibration. |\n\nA dash means the measure is undefined: D2 for constant outcomes, both Ginis\nfor zero loss, normalized Gini for constant positive outcomes, and percentage\nerror when observed loss is zero. A/E is zero when loss is zero and predictions\nare positive. The following sections examine calibration and ranking in more detail.\n\n::: {#78cf8baf .cell execution_count=29}\n``` {.python .cell-code}\nfor component, predictions in (\n    (\"frequency\", frequency_predictions),\n    (\"severity\", severity_predictions),\n    (\"pure_premium\", pure_premium_predictions),\n):\n    print_frame(\n        f\"{component.replace('_', ' ').title()} test accuracy\",\n        evaluate_predictions(splits.test, component, predictions, selected_power),\n    )\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                                  Frequency test accuracy                                  </span>\n┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model    </span>┃<span style=\"font-weight: bold\"> weighted_deviance </span>┃<span style=\"font-weight: bold\">        D2 </span>┃<span style=\"font-weight: bold\"> actual_expected </span>┃<span style=\"font-weight: bold\"> raw_gini </span>┃<span style=\"font-weight: bold\"> normalized_gini </span>┃\n┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩\n│ GLUM     │          0.455855 │ 0.0474204 │          1.0037 │ 0.288986 │        0.299596 │\n│ LightGBM │           0.44905 │ 0.0616387 │         1.00237 │ 0.321931 │        0.333751 │\n└──────────┴───────────────────┴───────────┴─────────────────┴──────────┴─────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                                    Severity test accuracy                                     </span>\n┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model    </span>┃<span style=\"font-weight: bold\"> weighted_deviance </span>┃<span style=\"font-weight: bold\">           D2 </span>┃<span style=\"font-weight: bold\"> actual_expected </span>┃<span style=\"font-weight: bold\">  raw_gini </span>┃<span style=\"font-weight: bold\"> normalized_gini </span>┃\n┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩\n│ GLUM     │           1.32607 │  -0.00130283 │         1.00305 │ 0.0167918 │       0.0301712 │\n│ LightGBM │           1.32445 │ -8.12131e-05 │         1.01917 │ 0.0242464 │       0.0435656 │\n└──────────┴───────────────────┴──────────────┴─────────────────┴───────────┴─────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                                           Pure Premium test accuracy                                           </span>\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model                         </span>┃<span style=\"font-weight: bold\"> weighted_deviance </span>┃<span style=\"font-weight: bold\">        D2 </span>┃<span style=\"font-weight: bold\"> actual_expected </span>┃<span style=\"font-weight: bold\"> raw_gini </span>┃<span style=\"font-weight: bold\"> normalized_gini </span>┃\n┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩\n│ GLUM frequency x severity     │           73.9688 │ 0.0481088 │         1.00472 │ 0.313389 │        0.318931 │\n│ LightGBM frequency x severity │           73.3357 │ 0.0562561 │         1.02016 │ 0.333146 │        0.339038 │\n│ GLUM Tweedie                  │           74.0018 │ 0.0476844 │         1.01329 │ 0.313712 │        0.319259 │\n│ LightGBM Tweedie              │           73.6108 │ 0.0527154 │         1.11671 │ 0.327742 │        0.333538 │\n└───────────────────────────────┴───────────────────┴───────────┴─────────────────┴──────────┴─────────────────┘\n</pre>\n```\n:::\n:::\n\n\nThe severity table is the exception: both models sit at essentially zero D2\nand near-zero Gini against the constant-mean baseline, so the decomposed\npure-premium estimates are close to predicted frequency times a near-constant\naverage claim amount.\n\n::: {.callout-note collapse=\"true\"}\n## Look inside: `weighted_mean_deviance`\n\n`TARGET_SPECS[component]` selects Poisson deviance for frequency, Gamma\nfor severity, or Tweedie at the selected power for pure premium.\n`sklearn.metrics.mean_*_deviance` averages observation-level deviances with\nthe component's weights: exposure for frequency and pure premium, claim\ncount for severity. With exposure weights, a six-month policy counts half\nas much as a twelve-month policy. The same response, power, and weighting\nconvention are used for training and test evaluation.\n\n::: {#d8f641f1 .cell execution_count=30}\n``` {.python .cell-code}\nshow_source(weighted_mean_deviance)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef weighted_mean_deviance(\n    y_true: np.ndarray,\n    y_pred: np.ndarray,\n    weight: np.ndarray,\n    component: str,\n    tweedie_power: float,\n) -> float:\n    \"\"\"Compute the component-appropriate weighted mean deviance.\"\"\"\n    if component == \"frequency\":\n        return float(mean_poisson_deviance(y_true, y_pred, sample_weight=weight))\n    if component == \"severity\":\n        return float(mean_gamma_deviance(y_true, y_pred, sample_weight=weight))\n    return float(\n        mean_tweedie_deviance(\n            y_true,\n            y_pred,\n            sample_weight=weight,\n            power=tweedie_power,\n        )\n    )\n\n```\n:::\n:::\n\n\n:::\n\n## Check calibration in total and by segment\n\nA/E is $\\sum_i w_i y_i / \\sum_i w_i\\hat\\mu_i$, where $y_i$ and\n$\\hat\\mu_i$ are observed and predicted rates and $w_i$ is the component's\nweight. Multiplying by the weight recovers counts or claim amounts, as in\nthe training portfolio averages.\n\nA useful ranking can still charge too much or too little in total.\nPortfolio calibration compares predicted and observed totals; segment\ncalibration checks whether agreement holds within customer groups.\n\nThe tables report observed totals, predicted totals, and their ratio A/E\n(actual / expected) for all three components. An A/E of 1 means the totals\nmatch, but errors can cancel between groups. Allow for sampling uncertainty\nand compare rates by driver age and other meaningful segments or time periods.\n\n::: {#4ce04cdb .cell execution_count=31}\n``` {.python .cell-code}\nfor component, predictions in (\n    (\"frequency\", frequency_predictions),\n    (\"severity\", severity_predictions),\n    (\"pure_premium\", pure_premium_predictions),\n):\n    print_frame(\n        f\"{component.replace('_', ' ').title()} portfolio calibration\",\n        portfolio_calibration_table(splits.test, component, predictions),\n    )\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                              Frequency portfolio calibration                              </span>\n┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model    </span>┃<span style=\"font-weight: bold\"> observed_total </span>┃<span style=\"font-weight: bold\"> predicted_total </span>┃<span style=\"font-weight: bold\"> actual_expected </span>┃<span style=\"font-weight: bold\"> signed_percentage_error </span>┃\n┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━┩\n│ GLUM     │          5,298 │        5,278.48 │          1.0037 │               -0.368391 │\n│ LightGBM │          5,298 │        5,285.47 │         1.00237 │               -0.236437 │\n└──────────┴────────────────┴─────────────────┴─────────────────┴─────────────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                              Severity portfolio calibration                               </span>\n┏━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model    </span>┃<span style=\"font-weight: bold\"> observed_total </span>┃<span style=\"font-weight: bold\"> predicted_total </span>┃<span style=\"font-weight: bold\"> actual_expected </span>┃<span style=\"font-weight: bold\"> signed_percentage_error </span>┃\n┡━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━┩\n│ GLUM     │    9.83495e+06 │     9.80506e+06 │         1.00305 │               -0.303926 │\n│ LightGBM │    9.83495e+06 │     9.64996e+06 │         1.01917 │                -1.88097 │\n└──────────┴────────────────┴─────────────────┴─────────────────┴─────────────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                                       Pure Premium portfolio calibration                                       </span>\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model                         </span>┃<span style=\"font-weight: bold\"> observed_total </span>┃<span style=\"font-weight: bold\"> predicted_total </span>┃<span style=\"font-weight: bold\"> actual_expected </span>┃<span style=\"font-weight: bold\"> signed_percentage_error </span>┃\n┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━┩\n│ GLUM frequency x severity     │    9.83495e+06 │     9.78877e+06 │         1.00472 │               -0.469603 │\n│ LightGBM frequency x severity │    9.83495e+06 │     9.64061e+06 │         1.02016 │                 -1.9761 │\n│ GLUM Tweedie                  │    9.83495e+06 │     9.70597e+06 │         1.01329 │                -1.31147 │\n│ LightGBM Tweedie              │    9.83495e+06 │     8.80706e+06 │         1.11671 │                -10.4514 │\n└───────────────────────────────┴────────────────┴─────────────────┴─────────────────┴─────────────────────────┘\n</pre>\n```\n:::\n:::\n\n\n### Calibration by driver age\n\nTables give exact totals; the banded view reveals shape, crossings, and local\nfailures that summary statistics can hide. The shared `grouped_calibration`\nhelper bins policies by `pd.qcut(DrivAge, 10)` and reports the observed and\npredicted rate per band. For frequency the weight is exposure; for severity\nthe weight is claim count.\n\n::: {#80b3e80e .cell execution_count=32}\n``` {.python .cell-code}\nfig, axes = plt.subplots(1, 2, figsize=(13, 4.5))\nfor axis, component, predictions in (\n    (axes[0], \"frequency\", frequency_predictions),\n    (axes[1], \"severity\", severity_predictions),\n):\n    calibration = grouped_calibration(splits.test, component, predictions)\n    x = np.arange(len(calibration))\n    axis.plot(\n        x,\n        calibration[\"observed\"],\n        \"o-\",\n        color=MODEL_COLORS[\"observed\"],\n        label=\"observed\",\n    )\n    for name in predictions:\n        axis.plot(\n            x, calibration[name], \"--\", color=MODEL_COLORS[name], label=name\n        )\n    axis.set_title(f\"{component.title()} by driver age\")\n    axis.set_xlabel(\"Driver-age band\")\n    axis.set_ylabel(\"Rate\")\n    axis.set_xticks(x)\n    axis.set_xticklabels(calibration.index.astype(str), rotation=45, ha=\"right\")\n    axis.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/cell-33-output-1.png){width=1238 height=422}\n:::\n:::\n\n\n## Inspect single-model lift by predicted-risk decile\n\nLift checks whether observed pure premium rises as predicted risk rises,\nand whether observed and predicted levels agree within each risk band.\nSort test policies from lowest to highest predicted risk, then divide their\nexposure into ten equal bins (deciles). Equal exposure accounts for different\npolicy durations.\n\nThe table shows the observed and predicted pure premium in each decile.\nJudge irregular patterns and gaps with the volume of data and sampling\nuncertainty in mind; one extreme decile is weak evidence for choosing a model.\n\n::: {#06d6da02 .cell execution_count=33}\n``` {.python .cell-code}\nlift_demo = exposure_balanced_lift_table(\n    y_test, pure_premium_predictions[\"LightGBM Tweedie\"], exposure\n)\nprint_frame(\"LightGBM Tweedie: per-decile lift\", lift_demo)\nprint_frame(\n    \"Pure-premium lift ranges\",\n    lift_diagnostics(y_test, pure_premium_predictions, exposure),\n)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">          LightGBM Tweedie: per-decile lift           </span>\n┏━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> decile </span>┃<span style=\"font-weight: bold\"> exposure </span>┃<span style=\"font-weight: bold\"> observed_rate </span>┃<span style=\"font-weight: bold\"> predicted_rate </span>┃\n┡━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━┩\n│      1 │ 7,146.15 │       43.0693 │        47.0157 │\n│      2 │ 7,146.15 │       75.8507 │        64.0309 │\n│      3 │ 7,146.15 │       77.4844 │        74.3736 │\n│      4 │ 7,146.15 │       97.9476 │        82.5571 │\n│      5 │ 7,146.15 │       90.0106 │         91.034 │\n│      6 │ 7,146.15 │       118.838 │        101.446 │\n│      7 │ 7,146.15 │       123.819 │        116.539 │\n│      8 │ 7,146.15 │        178.43 │        141.689 │\n│      9 │ 7,146.15 │       204.871 │        181.523 │\n│     10 │ 7,146.15 │        365.94 │        332.213 │\n└────────┴──────────┴───────────────┴────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                                             Pure-premium lift ranges                                              </span>\n┏━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model         </span>┃<span style=\"font-weight: bold\"> observed_fir… </span>┃<span style=\"font-weight: bold\"> observed_last </span>┃<span style=\"font-weight: bold\"> observed_range </span>┃<span style=\"font-weight: bold\"> predicted_fi… </span>┃<span style=\"font-weight: bold\"> predicted_last </span>┃<span style=\"font-weight: bold\"> predicted_ra… </span>┃\n┡━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩\n│ GLUM          │       55.0821 │       365.034 │        309.951 │       58.0064 │        364.992 │       306.985 │\n│ frequency x   │               │               │                │               │                │               │\n│ severity      │               │               │                │               │                │               │\n│ LightGBM      │       53.8566 │       376.457 │        322.601 │       52.4451 │        387.741 │       335.296 │\n│ frequency x   │               │               │                │               │                │               │\n│ severity      │               │               │                │               │                │               │\n│ GLUM Tweedie  │       50.9969 │       374.494 │        323.497 │        59.611 │        365.001 │        305.39 │\n│ LightGBM      │       43.0693 │        365.94 │        322.871 │       47.0157 │        332.213 │       285.197 │\n│ Tweedie       │               │               │                │               │                │               │\n└───────────────┴───────────────┴───────────────┴────────────────┴───────────────┴────────────────┴───────────────┘\n</pre>\n```\n:::\n:::\n\n\nThe summary `lift_diagnostics` table below only lists the first and last\ndecile plus the range; the full per-decile table above is what those come\nfrom.\n\n::: {.callout-note collapse=\"true\"}\n## Look inside: `exposure_balanced_lift_table`\n\n::: {#d0f08bed .cell execution_count=34}\n``` {.python .cell-code}\nshow_source(exposure_balanced_lift_table)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef exposure_balanced_lift_table(\n    y_true_rate: np.ndarray,\n    y_pred_rate: np.ndarray,\n    exposure: np.ndarray,\n    n_bins: int = 10,\n) -> pd.DataFrame:\n    \"\"\"Aggregate tied scores first, then split blocks across equal-exposure bins.\"\"\"\n    y_true_rate = np.asarray(y_true_rate, dtype=float)\n    y_pred_rate = np.asarray(y_pred_rate, dtype=float)\n    exposure = np.asarray(exposure, dtype=float)\n    if not isinstance(n_bins, (int, np.integer)) or n_bins < 1:\n        raise ValueError(\"n_bins must be a positive integer\")\n    if (\n        exposure.ndim != 1\n        or exposure.size == 0\n        or any(values.shape != exposure.shape for values in (y_true_rate, y_pred_rate))\n    ):\n        raise ValueError(\"rates and exposure must be aligned nonempty 1D arrays\")\n    if not np.all(np.isfinite(exposure) & (exposure > 0)) or not np.isfinite(\n        exposure.sum()\n    ):\n        raise ValueError(\"exposure must be finite and positive\")\n    if any(\n        np.any(~np.isfinite(values) | (values < 0))\n        for values in (y_true_rate, y_pred_rate)\n    ):\n        raise ValueError(\"rates must be finite and nonnegative\")\n\n    order = np.argsort(y_pred_rate, kind=\"stable\")\n    _, starts = np.unique(y_pred_rate[order], return_index=True)\n    cumulative_exposure = np.r_[\n        0.0, np.cumsum(np.add.reduceat(exposure[order], starts))\n    ]\n    cumulative_observed = np.r_[\n        0.0, np.cumsum(np.add.reduceat(exposure[order] * y_true_rate[order], starts))\n    ]\n    cumulative_predicted = np.r_[\n        0.0, np.cumsum(np.add.reduceat(exposure[order] * y_pred_rate[order], starts))\n    ]\n    boundaries = np.linspace(0, cumulative_exposure[-1], n_bins + 1)\n    observed = np.interp(boundaries, cumulative_exposure, cumulative_observed)\n    predicted = np.interp(boundaries, cumulative_exposure, cumulative_predicted)\n    bin_exposure = np.diff(boundaries)\n    return pd.DataFrame(\n        {\n            \"exposure\": bin_exposure,\n            \"observed_rate\": np.diff(observed) / bin_exposure,\n            \"predicted_rate\": np.diff(predicted) / bin_exposure,\n        },\n        index=pd.RangeIndex(1, n_bins + 1, name=\"decile\"),\n    )\n\n```\n:::\n:::\n\n\n:::\n\n### Per-model lift diagrams\n\nFor each model, the gap between observed and predicted decile means shows\ncalibration differences. The observed range across deciles shows how well\nthe model separates lower and higher risks.\n\n::: {#90c13fdb .cell execution_count=35}\n``` {.python .cell-code}\nfig, axes = plt.subplots(2, 2, figsize=(13, 9), sharex=True)\nfor axis, (name, prediction) in zip(axes.flat, pure_premium_predictions.items()):\n    lift = exposure_balanced_lift_table(y_test, prediction, exposure)\n    lift_axis = lift.index\n    axis.plot(\n        lift_axis,\n        lift[\"observed_rate\"],\n        \"o-\",\n        color=MODEL_COLORS[\"observed\"],\n        label=\"observed\",\n    )\n    axis.plot(\n        lift_axis,\n        lift[\"predicted_rate\"],\n        \"s--\",\n        color=MODEL_COLORS[name],\n        label=\"predicted\",\n    )\n    axis.set_title(name)\n    axis.set_xlabel(\"Exposure-balanced decile\")\n    axis.set_ylabel(\"Pure premium\")\n    axis.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/cell-36-output-1.png){width=1238 height=854}\n:::\n:::\n\n\n## Test ranking ability with Lorenz curves and Gini\n\nSort test policies from low to high predicted pure premium. The ordered\nLorenz curve plots cumulative exposure share against cumulative observed\nloss share in that order. Ties form a single block, so row order within a\ntie cannot change the curve. The diagonal represents no ranking information,\nincluding constant predictions.\n\nA curve below the diagonal means that policies ranked as lower risk account\nfor a smaller share of losses than exposure. Higher positive Gini is better,\nbut inspect the full curve: one model's curve dominates another only when\nit stays below it without crossing.\n\n### Compute the Gini coefficient by hand\n\nOutcome inequality and prediction ranking are different quantities.\nThe Gini from ordering on observed outcomes is the denominator of the\nnormalized prediction-ranked Gini. For a model's ascending prediction\norder, raw Gini is twice the signed area between the diagonal and its\ntie-aware Lorenz curve:\n\n$$\nG=2\\int_0^1[u-L(u)]\\,du.\n$$\n\nHere $u$ is cumulative exposure share and $L(u)$ is the corresponding\ncumulative observed loss share.\n\nFor equal weights, outcomes `[0, 2]` and scores `[1, 2]` give signed area\n0.25, raw Gini 0.5, and normalized Gini 1. Constant scores give raw Gini 0.\nReversing the two scores gives raw Gini -0.5 while outcome inequality stays 0.5.\n\nTie-permutation invariance, asserted on the test set:\n\n::: {#cda6a3ca .cell execution_count=36}\n``` {.python .cell-code}\nref_pred = pure_premium_predictions[\"LightGBM Tweedie\"]\nnp.testing.assert_allclose(\n    gini(y_test, ref_pred, exposure),\n    gini(y_test[::-1], ref_pred[::-1], exposure[::-1]),\n    rtol=1e-12,\n    atol=1e-12,\n)\n```\n:::\n\n\n### Ranking survives a change of scale\n\nA strictly increasing transformation preserves ranks and therefore Gini.\nTaking the log of positive predictions demonstrates this below. The\ntransformed values are ranking scores; they are not pure-premium estimates\nto use in a tariff. Two models with the same Gini can predict different totals.\n\n::: {#be2c347d .cell execution_count=37}\n``` {.python .cell-code}\nraw = pure_premium_predictions[\"LightGBM Tweedie\"]\nprint(f\"Gini on rates:        {gini(y_test, raw, exposure):.6f}\")\nprint(f\"Gini on log(rates):   {gini(y_test, np.log(raw), exposure):.6f}\")\nnp.testing.assert_allclose(\n    gini(y_test, raw, exposure), gini(y_test, np.log(raw), exposure),\n    rtol=1e-12, atol=1e-12,\n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nGini on rates:        0.327742\nGini on log(rates):   0.327742\n```\n:::\n:::\n\n\n### Compare all four pure-premium predictions\n\n::: {#9fea628b .cell execution_count=38}\n``` {.python .cell-code}\nprint_frame(\n    \"Pure-premium Lorenz dominance\",\n    lorenz_dominance_table(y_test, pure_premium_predictions, exposure),\n)\nprint_frame(\n    \"Pure-premium accuracy and Gini\",\n    evaluate_predictions(\n        splits.test,\n        \"pure_premium\",\n        pure_premium_predictions,\n        selected_power,\n    ),\n)\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                              Pure-premium Lorenz dominance                               </span>\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model_a                       </span>┃<span style=\"font-weight: bold\"> model_b                       </span>┃<span style=\"font-weight: bold\"> result                 </span>┃\n┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━┩\n│ GLUM frequency x severity     │ LightGBM frequency x severity │ crossing; no dominance │\n│ GLUM frequency x severity     │ GLUM Tweedie                  │ crossing; no dominance │\n│ GLUM frequency x severity     │ LightGBM Tweedie              │ crossing; no dominance │\n│ LightGBM frequency x severity │ GLUM Tweedie                  │ crossing; no dominance │\n│ LightGBM frequency x severity │ LightGBM Tweedie              │ crossing; no dominance │\n│ GLUM Tweedie                  │ LightGBM Tweedie              │ crossing; no dominance │\n└───────────────────────────────┴───────────────────────────────┴────────────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                                         Pure-premium accuracy and Gini                                         </span>\n┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> model                         </span>┃<span style=\"font-weight: bold\"> weighted_deviance </span>┃<span style=\"font-weight: bold\">        D2 </span>┃<span style=\"font-weight: bold\"> actual_expected </span>┃<span style=\"font-weight: bold\"> raw_gini </span>┃<span style=\"font-weight: bold\"> normalized_gini </span>┃\n┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩\n│ GLUM frequency x severity     │           73.9688 │ 0.0481088 │         1.00472 │ 0.313389 │        0.318931 │\n│ LightGBM frequency x severity │           73.3357 │ 0.0562561 │         1.02016 │ 0.333146 │        0.339038 │\n│ GLUM Tweedie                  │           74.0018 │ 0.0476844 │         1.01329 │ 0.313712 │        0.319259 │\n│ LightGBM Tweedie              │           73.6108 │ 0.0527154 │         1.11671 │ 0.327742 │        0.333538 │\n└───────────────────────────────┴───────────────────┴───────────┴─────────────────┴──────────┴─────────────────┘\n</pre>\n```\n:::\n:::\n\n\n### The Lorenz curve for every model\n\n::: {#dcc28bc5 .cell execution_count=39}\n``` {.python .cell-code}\nfig, axis = plt.subplots(figsize=(7, 6))\naxis.plot([0, 1], [0, 1], ls=\":\", color=\"grey\", label=\"diagonal\")\nfor name, prediction in pure_premium_predictions.items():\n    x, y = lorenz_curve(y_test, prediction, exposure)\n    axis.plot(\n        x,\n        y,\n        color=MODEL_COLORS[name],\n        label=f\"{name} (Gini {gini(y_test, prediction, exposure):.3f})\",\n    )\naxis.set_xlabel(\"Cumulative exposure share\")\naxis.set_ylabel(\"Cumulative observed loss share\")\naxis.set_title(\"Pure-premium ordered Lorenz curves\")\naxis.legend(loc=\"lower right\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/cell-40-output-1.png){width=589 height=523}\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Look inside: `lorenz_curve` and `gini`\n\nThe area formula equals $1-2\\,\\mathrm{AUC}$, where AUC is the area under\nthe same polygonal curve. It also equals the midrank form\n$G=2\\sum_b T_b\\bar F_b/\\sum_b T_b-1$,\nwhere tied block $b$ has exposure $w_b$, weighted observed loss $T_b$,\npreceding exposure $W_{b-1}$, total exposure $W$, and exposure-share midpoint\n$\\bar F_b=(W_{b-1}+w_b/2)/W$.\nBoth aggregate identical scores first. Normalization divides by\n`gini(y_test, y_test, exposure)` and does not change the model ordering.\n\nWhen comparing software, check ascending versus descending order, raw\nversus normalized Gini, exposure weights, and ties. A missing factor of\ntwo can cancel in a normalized ratio while still giving the wrong raw Gini.\n\n::: {#86ba694b .cell execution_count=40}\n``` {.python .cell-code}\nshow_source(lorenz_curve)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef lorenz_curve(\n    y_true_rate: np.ndarray,\n    y_pred_rate: np.ndarray,\n    weight: np.ndarray,\n) -> tuple[np.ndarray, np.ndarray]:\n    \"\"\"Return a low-to-high Lorenz curve including both endpoints.\n\n    Tied predictions are aggregated into a single block so the curve is\n    permutation-invariant. The block midpoint is reached once, giving a\n    straight line across the tied block (the standard convention when\n    average ranks are used).\n    \"\"\"\n    y_true_rate, weight = _validated_observations(y_true_rate, weight)\n    y_pred_rate = _validated_prediction(y_pred_rate, y_true_rate, ranking=True)\n    order = np.argsort(y_pred_rate, kind=\"stable\")\n    sorted_pred = y_pred_rate[order]\n    sorted_weight = weight[order]\n    sorted_observed = y_true_rate[order]\n    _, starts = np.unique(sorted_pred, return_index=True)\n    block_weight = np.add.reduceat(sorted_weight, starts)\n    block_observed = np.add.reduceat(sorted_weight * sorted_observed, starts)\n    cumulative_weight = np.r_[0.0, np.cumsum(block_weight)]\n    cumulative_loss = np.r_[0.0, np.cumsum(block_observed)]\n    cumulative_weight /= cumulative_weight[-1]\n    if cumulative_loss[-1] > 0:\n        if np.all(y_true_rate == y_true_rate[0]):\n            return cumulative_weight, cumulative_weight.copy()\n        cumulative_loss /= cumulative_loss[-1]\n    return cumulative_weight, cumulative_loss\n\n```\n:::\n:::\n\n\n::: {#037cf702 .cell execution_count=41}\n``` {.python .cell-code}\nshow_source(gini)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef gini(\n    y_true_rate: np.ndarray,\n    y_pred_rate: np.ndarray,\n    weight: np.ndarray,\n) -> float:\n    \"\"\"Twice the signed area between the diagonal and validated Lorenz curve.\n\n    Tied scores share a straight segment. Zero loss has undefined Gini;\n    constant positive outcomes have Gini zero.\n    \"\"\"\n    cumulative_weight, cumulative_loss = lorenz_curve(y_true_rate, y_pred_rate, weight)\n    if cumulative_loss[-1] <= 0:\n        return float(\"nan\")\n    return float(\n        2 * np.trapezoid(cumulative_weight - cumulative_loss, cumulative_weight)\n    )\n\n```\n:::\n:::\n\n\n:::\n\n## Use double lift to examine where models disagree\n\nTwo models can have similar aggregate accuracy but disagree sharply\nfor individual policies. Double lift focuses attention on disagreements.\n\nOrder policies by each model-A/model-B pure-premium ratio and\ncompare observed rates across equal-exposure ratio deciles.\n\nLow A/B ratios mean A predicts less relative to B; high ratios mean A\npredicts more relative to B. Compare observed levels with both model\ncurves in each bin. Rising observations alone do not favour A: with equal\nweights, observed `[1, 2, 4]`, A `[0.5, 2, 8]`, and B `[1, 2, 4]`, both\nthe ratios and observations rise, yet B matches every observed level.\nUse the observed gaps alongside uncertainty and deviance when comparing models.\n\n::: {#5f4176b0 .cell execution_count=42}\n``` {.python .cell-code}\nchosen_pairs = [\n    (\"GLUM frequency x severity\", \"LightGBM frequency x severity\"),\n    (\"GLUM Tweedie\", \"LightGBM Tweedie\"),\n    (\"GLUM frequency x severity\", \"GLUM Tweedie\"),\n    (\"LightGBM frequency x severity\", \"LightGBM Tweedie\"),\n]\nfor model_a, model_b in chosen_pairs:\n    print_frame(\n        f\"Double lift: {model_a} / {model_b}\",\n        exposure_balanced_double_lift_table(\n            y_test,\n            pure_premium_predictions[model_a],\n            pure_premium_predictions[model_b],\n            exposure,\n        ),\n    )\n```\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">        Double lift: GLUM frequency x severity / LightGBM frequency x severity        </span>\n┏━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> decile </span>┃<span style=\"font-weight: bold\"> exposure </span>┃<span style=\"font-weight: bold\"> observed_rate </span>┃<span style=\"font-weight: bold\"> model_a_rate </span>┃<span style=\"font-weight: bold\"> model_b_rate </span>┃<span style=\"font-weight: bold\"> prediction_ratio </span>┃\n┡━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩\n│      1 │ 7,146.15 │       237.205 │      148.308 │      243.468 │         0.659852 │\n│      2 │ 7,146.15 │       146.766 │      121.874 │      149.466 │         0.816236 │\n│      3 │ 7,146.15 │       155.039 │        122.4 │      137.056 │         0.893396 │\n│      4 │ 7,146.15 │       140.791 │       124.81 │      130.336 │         0.957735 │\n│      5 │ 7,146.15 │       105.231 │      125.898 │      123.717 │          1.01795 │\n│      6 │ 7,146.15 │       107.398 │      126.853 │      117.592 │          1.07893 │\n│      7 │ 7,146.15 │       143.954 │       130.26 │      113.717 │          1.14566 │\n│      8 │ 7,146.15 │       101.197 │      131.069 │          107 │          1.22516 │\n│      9 │ 7,146.15 │       102.998 │      144.321 │      108.115 │          1.33486 │\n│     10 │ 7,146.15 │       135.682 │      194.003 │      118.596 │          1.61675 │\n└────────┴──────────┴───────────────┴──────────────┴──────────────┴──────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                     Double lift: GLUM Tweedie / LightGBM Tweedie                     </span>\n┏━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> decile </span>┃<span style=\"font-weight: bold\"> exposure </span>┃<span style=\"font-weight: bold\"> observed_rate </span>┃<span style=\"font-weight: bold\"> model_a_rate </span>┃<span style=\"font-weight: bold\"> model_b_rate </span>┃<span style=\"font-weight: bold\"> prediction_ratio </span>┃\n┡━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩\n│      1 │ 7,146.15 │       216.902 │      146.675 │      216.792 │         0.707328 │\n│      2 │ 7,146.15 │       153.612 │      126.346 │      143.376 │         0.882716 │\n│      3 │ 7,146.15 │       130.411 │      122.833 │      126.644 │         0.970558 │\n│      4 │ 7,146.15 │       148.798 │      122.081 │      117.469 │          1.03972 │\n│      5 │ 7,146.15 │       101.573 │       121.56 │      110.419 │          1.10109 │\n│      6 │ 7,146.15 │        165.26 │      124.171 │      106.873 │          1.16224 │\n│      7 │ 7,146.15 │       98.0258 │      124.318 │      101.223 │          1.22857 │\n│      8 │ 7,146.15 │       113.985 │      129.148 │      98.7896 │          1.30738 │\n│      9 │ 7,146.15 │       103.393 │      136.598 │      96.3291 │          1.41824 │\n│     10 │ 7,146.15 │         144.3 │      204.479 │      114.505 │          1.71789 │\n└────────┴──────────┴───────────────┴──────────────┴──────────────┴──────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">                Double lift: GLUM frequency x severity / GLUM Tweedie                 </span>\n┏━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> decile </span>┃<span style=\"font-weight: bold\"> exposure </span>┃<span style=\"font-weight: bold\"> observed_rate </span>┃<span style=\"font-weight: bold\"> model_a_rate </span>┃<span style=\"font-weight: bold\"> model_b_rate </span>┃<span style=\"font-weight: bold\"> prediction_ratio </span>┃\n┡━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩\n│      1 │ 7,146.15 │       129.733 │      139.488 │      170.796 │         0.821089 │\n│      2 │ 7,146.15 │       136.229 │      128.087 │      142.719 │         0.897713 │\n│      3 │ 7,146.15 │       143.365 │      128.021 │       136.84 │         0.935691 │\n│      4 │ 7,146.15 │       138.573 │      121.343 │      125.474 │         0.967277 │\n│      5 │ 7,146.15 │       141.356 │      117.848 │      118.474 │          0.99474 │\n│      6 │ 7,146.15 │       110.509 │      122.184 │      119.805 │          1.01992 │\n│      7 │ 7,146.15 │       134.374 │      127.226 │      121.541 │          1.04666 │\n│      8 │ 7,146.15 │       109.382 │      136.246 │      126.171 │          1.07968 │\n│      9 │ 7,146.15 │       133.352 │      152.281 │      135.539 │          1.12303 │\n│     10 │ 7,146.15 │       199.386 │      197.073 │      160.851 │          1.21967 │\n└────────┴──────────┴───────────────┴──────────────┴──────────────┴──────────────────┘\n</pre>\n```\n:::\n\n::: {.cell-output .cell-output-display}\n```{=html}\n<pre style=\"white-space:pre;overflow-x:auto;line-height:normal;font-family:Menlo,'DejaVu Sans Mono',consolas,'Courier New',monospace\"><span style=\"font-style: italic\">            Double lift: LightGBM frequency x severity / LightGBM Tweedie             </span>\n┏━━━━━━━━┳━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━┓\n┃<span style=\"font-weight: bold\"> decile </span>┃<span style=\"font-weight: bold\"> exposure </span>┃<span style=\"font-weight: bold\"> observed_rate </span>┃<span style=\"font-weight: bold\"> model_a_rate </span>┃<span style=\"font-weight: bold\"> model_b_rate </span>┃<span style=\"font-weight: bold\"> prediction_ratio </span>┃\n┡━━━━━━━━╇━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━┩\n│      1 │ 7,146.15 │       148.363 │      124.126 │      171.296 │         0.736046 │\n│      2 │ 7,146.15 │       144.992 │      117.221 │      134.105 │         0.874937 │\n│      3 │ 7,146.15 │       105.283 │      117.648 │       124.27 │         0.947247 │\n│      4 │ 7,146.15 │       143.219 │      117.491 │      116.903 │          1.00515 │\n│      5 │ 7,146.15 │       106.391 │        119.5 │      113.086 │          1.05686 │\n│      6 │ 7,146.15 │       111.753 │      121.923 │      110.035 │          1.10805 │\n│      7 │ 7,146.15 │       125.083 │      125.951 │      108.248 │           1.1637 │\n│      8 │ 7,146.15 │       120.379 │      133.375 │       108.29 │          1.23182 │\n│      9 │ 7,146.15 │       156.128 │      147.002 │      110.733 │          1.32682 │\n│     10 │ 7,146.15 │        214.67 │      224.827 │      135.455 │          1.61479 │\n└────────┴──────────┴───────────────┴──────────────┴──────────────┴──────────────────┘\n</pre>\n```\n:::\n:::\n\n\n::: {.callout-note collapse=\"true\"}\n## Look inside: `exposure_balanced_double_lift_table`\n\nThe helper sorts by A/B ratio and combines equal ratios into tied blocks.\nIt interpolates cumulative weighted totals at equal-exposure boundaries,\nspreading each tied block proportionally across bins. This makes the table\nindependent of row order within ties. No bin, including either endpoint,\nis forced to match observations.\n\n::: {#129bd238 .cell execution_count=43}\n``` {.python .cell-code}\nshow_source(exposure_balanced_double_lift_table)\n```\n\n::: {.cell-output .cell-output-display .cell-output-markdown}\n```python\ndef exposure_balanced_double_lift_table(\n    y_true_rate: np.ndarray,\n    model_a_prediction: np.ndarray,\n    model_b_prediction: np.ndarray,\n    exposure: np.ndarray,\n    n_bins: int = 10,\n) -> pd.DataFrame:\n    \"\"\"Bin low-to-high A/B ratios, distributing tied blocks proportionally.\"\"\"\n    y_true_rate = np.asarray(y_true_rate, dtype=float)\n    model_a_prediction = np.asarray(model_a_prediction, dtype=float)\n    model_b_prediction = np.asarray(model_b_prediction, dtype=float)\n    exposure = np.asarray(exposure, dtype=float)\n    if not isinstance(n_bins, (int, np.integer)) or n_bins < 1:\n        raise ValueError(\"n_bins must be a positive integer\")\n    if (\n        exposure.ndim != 1\n        or exposure.size == 0\n        or any(\n            values.shape != exposure.shape\n            for values in (y_true_rate, model_a_prediction, model_b_prediction)\n        )\n    ):\n        raise ValueError(\"rates and exposure must be aligned nonempty 1D arrays\")\n    if np.any(~np.isfinite(y_true_rate) | (y_true_rate < 0)):\n        raise ValueError(\"observed rates must be finite and nonnegative\")\n    if not np.all(np.isfinite(exposure) & (exposure > 0)) or not np.isfinite(\n        exposure.sum()\n    ):\n        raise ValueError(\"exposure must be finite and positive\")\n    if not np.all(np.isfinite(model_a_prediction) & (model_a_prediction > 0)):\n        raise ValueError(\"model_a_prediction must be finite and positive\")\n    if not np.all(np.isfinite(model_b_prediction) & (model_b_prediction > 0)):\n        raise ValueError(\"model_b_prediction must be finite and positive\")\n    with np.errstate(over=\"ignore\", under=\"ignore\"):\n        ratio = model_a_prediction / model_b_prediction\n    if np.any(~np.isfinite(ratio) | (ratio <= 0)):\n        raise ValueError(\"prediction ratios must be finite and positive\")\n    order = np.argsort(ratio, kind=\"stable\")\n    _, starts = np.unique(ratio[order], return_index=True)\n    cumulative_exposure = np.r_[\n        0.0, np.cumsum(np.add.reduceat(exposure[order], starts))\n    ]\n    boundaries = np.linspace(0, cumulative_exposure[-1], n_bins + 1)\n    bin_exposure = np.diff(boundaries)\n\n    def rates(values: np.ndarray) -> np.ndarray:\n        cumulative = np.r_[\n            0.0, np.cumsum(np.add.reduceat(exposure[order] * values[order], starts))\n        ]\n        return (\n            np.diff(np.interp(boundaries, cumulative_exposure, cumulative))\n            / bin_exposure\n        )\n\n    return pd.DataFrame(\n        {\n            \"exposure\": bin_exposure,\n            \"observed_rate\": rates(y_true_rate),\n            \"model_a_rate\": rates(model_a_prediction),\n            \"model_b_rate\": rates(model_b_prediction),\n            \"prediction_ratio\": rates(ratio),\n        },\n        index=pd.RangeIndex(1, n_bins + 1, name=\"decile\"),\n    )\n\n```\n:::\n:::\n\n\nThe `prediction_ratio` column averages individual ratios, not group means:\nin one equal-weight bin, A `[1, 4]` and B `[1, 2]` give a mean ratio of 1.5,\nwhile the ratio of group means is $5/3$.\n:::\n\n### Double-lift panels\n\nThese four panels use the same model pairs as the CLI's `save_core_figures`.\nA/B ratio sorting puts the lowest relative A predictions in decile 1 and\nthe highest in decile 10. Neither end automatically favours either model.\n\n::: {#9b4955cc .cell execution_count=44}\n``` {.python .cell-code}\nfig, axes = plt.subplots(2, 2, figsize=(13, 9), sharex=True)\nfor axis, (model_a, model_b) in zip(axes.flat, chosen_pairs):\n    lift = exposure_balanced_double_lift_table(\n        y_test,\n        pure_premium_predictions[model_a],\n        pure_premium_predictions[model_b],\n        exposure,\n    )\n    axis.plot(\n        lift.index,\n        lift[\"observed_rate\"],\n        \"o-\",\n        color=MODEL_COLORS[\"observed\"],\n        label=\"observed\",\n    )\n    axis.plot(\n        lift.index,\n        lift[\"model_a_rate\"],\n        \"s--\",\n        color=MODEL_COLORS[model_a],\n        label=f\"A: {model_a}\",\n    )\n    axis.plot(\n        lift.index,\n        lift[\"model_b_rate\"],\n        \"^:\",\n        color=MODEL_COLORS[model_b],\n        label=f\"B: {model_b}\",\n    )\n    axis.set_title(f\"{model_a} / {model_b}\")\n    axis.set_xlabel(\"A/B ratio decile\")\n    axis.set_ylabel(\"Pure premium\")\n    axis.legend()\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/cell-45-output-1.png){width=1238 height=854}\n:::\n:::\n\n\n## Inspect the full prediction distribution with hexbin plots\n\nThe scores above summarize performance across policies. Hexbin plots group\nnearby points into hexagons to show where policies concentrate. Plotting\npredicted against observed pure premium, and residuals against predictions,\nreveals the claim-free mass and the spread of outcomes behind those scores.\n\nFor each of the four pure-premium models, plot predicted vs\nobserved hexbins on linear and log axes, and residuals on linear axes.\nLinear views show the bulk; the positive-loss log-log view describes the\nobserved tail. Colour encodes the policy count per bin on a log scale,\nusing the perceptually uniform, colourblind-safe cividis colormap and one\nshared colour scale per figure. These bins count policies, while the deviance\nand lift tables use exposure weights.\n\n### Predicted vs observed, linear axes\n\nThe bulk of the data sits in the span of the predictions; the horizontal\nband at observed = 0 is the claim-free mass of the portfolio, not an error.\nThe panel uses the predicted-value range on x and includes zero on observed y, so a\nhandful of very large observed losses do not squash the bulk; the largest\noutliers lie off-view by construction, and the log-log panel below shows\nthem.\n\n::: {#0d216247 .cell execution_count=45}\n``` {.python .cell-code}\nhexbin_grid(\n    {\n        name: (prediction, y_test)\n        for name, prediction in pure_premium_predictions.items()\n    },\n    \"Predicted pure premium\",\n    \"Observed pure premium\",\n    reference=\"diag\",\n    extent_mode=\"diag\",\n)\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/cell-46-output-1.png){width=1099 height=745}\n:::\n\n::: {.cell-output .cell-output-display execution_count=45}\n```\n(<Figure size 1248x864 with 5 Axes>,\n array([[<Axes: title={'center': 'GLUM frequency x severity'}, xlabel='Predicted pure premium', ylabel='Observed pure premium'>,\n         <Axes: title={'center': 'LightGBM frequency x severity'}, xlabel='Predicted pure premium', ylabel='Observed pure premium'>],\n        [<Axes: title={'center': 'GLUM Tweedie'}, xlabel='Predicted pure premium', ylabel='Observed pure premium'>,\n         <Axes: title={'center': 'LightGBM Tweedie'}, xlabel='Predicted pure premium', ylabel='Observed pure premium'>]],\n       dtype=object))\n```\n:::\n:::\n\n\n### Predicted vs observed, log axes\n\nThe log-log panel shows the spread of positive observed pure premiums\nagainst predictions. Hexagon widths are equal in log space, so each decade\nof observed loss gets comparable resolution.\n\nZeros cannot be logged, so this view excludes claim-free policies. The\npredictions still estimate pure premium across all outcomes; selecting\npositive losses does not turn them into severity predictions. This selected\nview cannot check mean calibration, and individual losses need not lie near\nthe identity line.\n\n::: {#454a021a .cell execution_count=46}\n``` {.python .cell-code}\npositive_loss = y_test > 0\nhexbin_grid(\n    {\n        name: (prediction[positive_loss], y_test[positive_loss])\n        for name, prediction in pure_premium_predictions.items()\n    },\n    \"Predicted pure premium (log scale)\",\n    \"Observed pure premium (log scale)\",\n    logx=True,\n    logy=True,\n    reference=\"diag\",\n)\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/cell-47-output-1.png){width=1089 height=746}\n:::\n\n::: {.cell-output .cell-output-display execution_count=46}\n```\n(<Figure size 1248x864 with 5 Axes>,\n array([[<Axes: title={'center': 'GLUM frequency x severity'}, xlabel='Predicted pure premium (log scale)', ylabel='Observed pure premium (log scale)'>,\n         <Axes: title={'center': 'LightGBM frequency x severity'}, xlabel='Predicted pure premium (log scale)', ylabel='Observed pure premium (log scale)'>],\n        [<Axes: title={'center': 'GLUM Tweedie'}, xlabel='Predicted pure premium (log scale)', ylabel='Observed pure premium (log scale)'>,\n         <Axes: title={'center': 'LightGBM Tweedie'}, xlabel='Predicted pure premium (log scale)', ylabel='Observed pure premium (log scale)'>]],\n       dtype=object))\n```\n:::\n:::\n\n\n### Residuals vs predicted, linear axes\n\nResiduals are observed minus predicted pure premium. Every claim-free policy\ntherefore lies on the stripe $-\\hat\\mu$, even for a correctly specified mean.\nNeither that stripe nor asymmetric residuals establishes overpricing.\nThe y-axis is clipped to a symmetric predicted span, so large positive\nresiduals can lie outside the panel. The densest visible band is not the\nconditional mean.\n\nJudge the mean with exposure-weighted calibration and lift tables that\nretain all outcomes, including zeros and the tail. A widening spread is\nexpected under the working variance models. Investigate departures of\nweighted observed means from predictions with uncertainty and segment\ncredibility in mind.\n\nFor multiplicative bias $E[Y\\mid X]=c\\hat\\mu$, the expected residual is\n$(c-1)\\hat\\mu$: even a simple scale error produces a sloped residual mean.\nA constant expected residual offset is instead additive,\n$E[Y\\mid X]=\\hat\\mu+a$. Curvature may warrant further investigation, but\nvisual stripes alone do not identify missing features. Recalibration\ninformed by this test audit requires a new evaluation cycle.\n\n::: {#6ff3c69c .cell execution_count=47}\n``` {.python .cell-code}\nhexbin_grid(\n    {\n        name: (prediction, y_test - prediction)\n        for name, prediction in pure_premium_predictions.items()\n    },\n    \"Predicted pure premium\",\n    \"Residual (observed - predicted)\",\n    reference=\"zero\",\n    extent_mode=\"residual\",\n)\n```\n\n::: {.cell-output .cell-output-display}\n![](pure_premium_tutorial_files/figure-html/cell-48-output-1.png){width=1110 height=745}\n:::\n\n::: {.cell-output .cell-output-display execution_count=47}\n```\n(<Figure size 1248x864 with 5 Axes>,\n array([[<Axes: title={'center': 'GLUM frequency x severity'}, xlabel='Predicted pure premium', ylabel='Residual (observed - predicted)'>,\n         <Axes: title={'center': 'LightGBM frequency x severity'}, xlabel='Predicted pure premium', ylabel='Residual (observed - predicted)'>],\n        [<Axes: title={'center': 'GLUM Tweedie'}, xlabel='Predicted pure premium', ylabel='Residual (observed - predicted)'>,\n         <Axes: title={'center': 'LightGBM Tweedie'}, xlabel='Predicted pure premium', ylabel='Residual (observed - predicted)'>]],\n       dtype=object))\n```\n:::\n:::\n\n\n## What this locked test showed {#sec-test-findings}\n\nOn this full-data run, LightGBM frequency × severity had test deviance\n73.34 and A/E 1.020. Direct LightGBM Tweedie had deviance 73.61 and A/E\n1.117. Deviance is close; the decomposed model is better calibrated in\ntotal. No recalibration was fitted to these results. They are a recorded\naudit, not a deployment choice. Relativities, fairness, and stability on\nlater periods remain further work.\n\n### Before choosing a model\n\nUse the test results to record which checks each candidate meets and which\nremain open:\n\n- Compare deviance at the same response and power, and judge whether the\n  improvement is large enough to matter.\n- Check total A/E and segment means with their uncertainty. In lift and\n  double-lift plots, compare observed levels with each model's predictions.\n- Read the full Lorenz curves alongside Gini; crossing curves leave the\n  ranking comparison unresolved.\n- Review the training tail and dispersion findings separately from mean\n  prediction. These checks do not establish a complete outcome distribution.\n- Review relativities, fairness, and stability on resamples or later periods.\n  Those checks remain further work in this tutorial.\n\nRecord this audit before changing the model. Any alternative family,\nrecalibration, or feature change needs development-data fitting and validation,\nfollowed by a new held-out audit using data that did not inform the change.\n\n",
    "supporting": [
      "pure_premium_tutorial_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}